### ISSUE TITLE
Ruby type error with NuGet updater

### ISSUE THREAD

**Issue by NickGraham101** [tinglesoftware/dependabot-azure-devops#1016]
**Describe the bug**
Ruby TypeError is thrown after Pull Requests creation for NuGet package update is attempted.  Docker updates that are attempted earlier succeed. 

```

	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb:39:in `new_branch_name'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator/branch_namer.rb:68:in `new_branch_name'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator.rb:306:in `azure_creator'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator.rb:236:in `create'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:833:in `block in <main>'
	from bin/update_script.rb:549:in `each'
	from bin/update_script.rb:549:in `<main>'
```

**To Reproduce**
1. Run a pipeline using the Azure DevOps template [here](https://github.com/NickGraham101/gandt-devops/blob/main/AzureDevOpsTemplates/Build/StageTemplates/dependabot-run.yml), the relevant step for this bug is:
```

    - task: dependabot@1
      condition: or(and(eq(variables['CheckScheduleName.RunDependabot'], 'true'), le(variables['System.JobAttempt'], 1), succeeded()), ${{ parameters.RunManually }})
      inputs:
        useConfigFile: true
        ${{ if eq(parameters.EnableDebug, true)  }}:
          extraEnvironmentVariables: 'EXCON_DEBUG=1'
 ```

**Expected behavior**
That the PR is raised. 

**Extension (please complete the following information):**
 - Host:  Azure DevOps
 - Version: 1.26.665

**Additional Context**
This may be related to Issue [999](https://github.com/tinglesoftware/dependabot-azure-devops/issues/999#issuecomment-1964847070)

**Comment by mburumaxwell** [comment]
You have provided the exception's stack trace but I do not see the message. Did you crop that by mistake?

**Comment by NickGraham101** [comment]
Apologies, didn’t realise the iPhone had a copy and paste limit, full message below

```
Updating project [/home/dependabot/dependabot-updater/tmp/nickgraham101/grahamandtonic/_git/grahamandtonic/src/grahamandtonic/grahamandtonic.csproj]
  Running for SDK-style project
    Found incorrect [PackageReference] version attribute in [src/grahamandtonic/grahamandtonic.csproj].
    Package [AutoMapper] could not be updated in [/home/dependabot/dependabot-updater/tmp/nickgraham101/grahamandtonic/_git/grahamandtonic/src/grahamandtonic/grahamandtonic.csproj] because it would cause a dependency conflict.
Update complete.
Submitting AutoMapper pull request for creation.
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/_types.rb:222:in `must': Passed `nil` into T.must (TypeError)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb:49:in `prefixes'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb:39:in `new_branch_name'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator/branch_namer.rb:68:in `new_branch_name'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator.rb:306:in `azure_creator'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator.rb:236:in `create'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:833:in `block in <main>'
	from bin/update_script.rb:549:in `each'
	from bin/update_script.rb:549:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1
```

**Comment by mburumaxwell** [comment]
This needs to be reported in the core repo.

**Comment by NickGraham101** [comment]
Thanks for the response, it’ll be a few days before I can do that as I don’t have access to the files they request for a new issue
