### ISSUE TITLE
Nuget updater error on .NET SDK version

### ISSUE THREAD

**Issue by OlliPasanen-Git** [tinglesoftware/dependabot-azure-devops#1066]
**Describe the bug**
I try to run dependabot task in a pipeline in our Azure Devops environment. Running the script for nuget packages give this error on every library:

```
running NuGet updater:
/opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/tmp/<path> --solution-or-project /home/dependabot/dependabot-updater/tmp/l<path> --dependency ClosedXML --new-version 0.102.2 --previous-version 0.101.0 --verbose
E, [2024-04-03T17:40:37.460877 #8] ERROR -- : Block argument of NuGetConfigCredentialHelpers::patch_nuget_config_for_action causes an exception A compatible .NET SDK was not found.

Requested SDK version: 7.0.202
global.json file: /home/dependabot/dependabot-updater/tmp/<path>/global.json

Installed SDKs:

Install the [7.0.202] .NET SDK or update [/home/dependabot/dependabot-updater/tmp/<path>/global.json] to match an installed SDK.

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
Unhandled exception: System.TypeInitializationException: The type initializer for 'NuGetUpdater.Core.MSBuildHelper' threw an exception.
 ---> System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxr_resolve_sdk2. There may be more details in stderr.
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory)
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NuGetUpdater.Core.MSBuildHelper.RegisterMSBuild() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 55
   at NuGetUpdater.Core.MSBuildHelper..cctor() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 36
```

I installed the requested .NET SDK ( 7.0.202) to the runner machine, but that had no effect. If the dependabot script is run inside docker container, it is understandable. To me it looks like the container should have that .NET version. Or is there some other way to fix this problem.

**Comment by OlliPasanen-Git** [comment]
If I use the 1.23.1-ci0018-image, my npm updates won't work. It seems that I could run them separately with different tasks and different images. However I have no glue how to configure this "target update ID" in the dependabot.yml file
<img width="417" alt="image" src="https://github.com/tinglesoftware/dependabot-azure-devops/assets/122795039/156fba9b-5bee-4d17-aa2e-a4e1d24570a4">

Could someone clarify that?

**Comment by mburumaxwell** [comment]
Most NuGet-related issues have been resolved in dependabot-core. If you are still experiencing issues, pin the `dockerImageTag` input to `1.24` as explained in #921.
This repository will be updated for the latest changes soon.

Closing this, use #921 to track any NuGet-related issues.
