### ISSUE TITLE
Can't auth to ACR

### ISSUE THREAD

**Issue by piotrlaczykowski** [tinglesoftware/dependabot-azure-devops#1178]
**Describe the bug**
Can't connect to ACR

**Categorization**
- [X] This is not a permissions issue (We cannot solve permission issues)

```text
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-docker-0.262.0/lib/dependabot/docker/update_checker.rb:208:in `rescue in tags_from_registry': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): iversparkcontainers.azurecr.io (Dependabot::PrivateSourceAuthenticationFailure)
```

Well I can't connect to ACR using this config:

_Basic `dependabot.yml` file with
minimum configuration for two package managers_

```yaml
registries:
  dockerhub: # Define access for a private registry
    type: docker-registry
    url: iversparkcontainers.azurecr.io
    username: ${{acr.pullpush.username}}
    password: ${{acr.pullpush.password}}
version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/docker/azure-agent"
    registries: "*"
    # Check for updates once a week
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/docker/base"
    registries: "*"
    # Check for updates once a week
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/docker/services"
    registries: "*"
    # Check for updates once a week
    schedule:
      interval: "daily"`
```

Maybe I am doing something wrong?
If I am it should be added to readme in my opinion

**Comment by cherealnice** [comment]
Adding to this: I've been debugging why I keep getting 401s from  https://pkgs.dev.azure.com/ when running update_script. I cannot figure out what is going on. I get a successful curl with base64 encoded `org:<PAT>` token with basic auth, but when I add the same token to my DEPENDABOT_EXTRA_CREDENTIALS it throws auth errors. Looking at the update script, it seems like [this](https://github.com/dependabot/dependabot-core/blob/b6c464a1f301a4f1280a26397e5d9f0e11e0bb43/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L124) should be using the same auth as my curl (see curl below). Is there any way to log the auth header to see what value the request is getting?

curl:
curl -L -H "Authorization: Basic <base64Encoded>" \
     -H "Accept: application/octet-stream" \
     -o my-package.tgz \
     -v \
     "https://pkgs.dev.azure.com/org/_packaging/eSmart/npm/registry/eslint"

docker command (I've tried 1.24, 1.27 and 1.29):
docker run --rm -i \
-e DEPENDABOT_PACKAGE_MANAGER=npm \
-e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=1 \
-e DEPENDABOT_DIRECTORY=/ \
-e DEPENDABOT_TARGET_BRANCH=main \
-e DEPENDABOT_EXTRA_CREDENTIALS='[{"type":"npm_registry","token":"<same token as curl>","replaces-base":true,"registry":"pkgs.dev.azure.com/org/_packaging/company/npm/registry/"}]' \
-e DEPENDABOT_FAIL_ON_EXCEPTION=true \
-e DEPENDABOT_CLOSE_PULL_REQUESTS=true \
-e AZURE_ORGANIZATION=org \
-e AZURE_PROJECT=project \
-e AZURE_REPOSITORY=repo \
-e AZURE_ACCESS_TOKEN=token \
-e AZURE_MERGE_STRATEGY=squash \
-e AZURE_SET_AUTO_COMPLETE=true \
ghcr.io/tinglesoftware/dependabot-updater-npm:1.29 update_script \

**Comment by mburumaxwell** [comment]
Seems like the issue is to do with authenticating against ACR in which case I don't understand how the PAT or NPM registry comes into play.

**Comment by rhyskoedijk** [comment]
I might be misunderstanding the problem or this could be completely unrelated, but something that stands out to me in the original post is that placeholder variable names in "username" wouldn't have replaced until https://github.com/tinglesoftware/dependabot-azure-devops/pull/1241 just recently. It's possible auth failed because it was literary using "${{acr.pullpush.username}}" as the username.

```yml
registries:
  dockerhub:
    type: docker-registry
    url: iversparkcontainers.azurecr.io
    username: ${{acr.pullpush.username}} # <-- this probably wouldn't have be transformed prior to 1.30.1
    password: ${{acr.pullpush.password}}
```

**Comment by mburumaxwell** [comment]
That too is correct because I had intentionally blocked the replacement of username until there was reason. Also, the `acr.pullpush.password` notation may not be translated correctly as compared to using `ACR_PULL_PUSH_PASSWORD`

**Comment by DaleMckeown** [comment]
@cherealnice Did you manage to resolve your NPM issue? I'm running into the exact same issue and whatever I try does not resolve it.

**Comment by DaleMckeown** [comment]
@cherealnice Headers can be seen when adding `EXCON_DEBUG=1` as an extra environment variable as shown below.

```
      - task: dependabot@1
        displayName: Run Dependabot
        inputs:
          mergeStrategy: squash
          setAutoComplete: true
          extraEnvironmentVariables: EXCON_DEBUG=1
```

In my case, the authorisation header does not appear to be being sent:

```
Checking if @uol/cwd 7.0.0 needs updating
excon.request
  :chunk_size          => 1048576
  :ciphers             => "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA:!DSS"
  :connect_timeout     => 5
  :debug_request       => true
  :debug_response      => true
  :dns_timeouts        => nil
  :headers             => {
    "Host"       => "pkgs.dev.azure.com"
    "User-Agent" => "dependabot-core/0.267.0 excon/0.111.0 ruby/3.3.1 (x86_64-linux) (+https://github.com/dependabot/dependabot-core)"
  }
  :host                => "pkgs.dev.azure.com"
  :hostname            => "pkgs.dev.azure.com"
  :idempotent          => true
  :instrumentor        => Excon::StandardInstrumentor
  :instrumentor_name   => "excon"
  :method              => :get
  :middlewares         => [
    Excon::Middleware::ResponseParser
    Excon::Middleware::Expects
    Excon::Middleware::Idempotent
    Excon::Middleware::Instrumentor
    Excon::Middleware::Mock
    Excon::Middleware::Decompress
    Excon::Middleware::RedirectFollower
  ]
  :mock                => false
  :nonblock            => true
  :omit_default_port   => true
  :path                => "/ORG/_packaging/PROJ/npm/registry/@uol%2Fcwd"
  :persistent          => false
  :port                => 443
  :query               => nil
  :read_timeout        => 20
  :resolv_resolver     => nil
  :retries_remaining   => 4
  :retry_errors        => [
    Excon::Error::Timeout
    Excon::Error::Socket
    Excon::Error::HTTPStatus
  ]
  :retry_limit         => 4
  :scheme              => "https"
  :ssl_uri_schemes     => [
    "https"
  ]

    "ActivityId"                    => "9b826497-9b78-4803-b226-531875e06122"
    "Cache-Control"                 => "no-cache"
    "Content-Length"                => "343"
    "Content-Type"                  => "application/json; charset=utf-8"
    "Date"                          => "Thu, 15 Aug 2024 15:13:35 GMT"
    "Expires"                       => "-1"
    "P3P"                           => "CP=\"CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT\""
    "Pragma"                        => "no-cache"
    "Request-Context"               => "appId=cid-v1:f5d75a35-28cc-4e72-8007-1cf59e01402f"
    "Strict-Transport-Security"     => "max-age=31536000; includeSubDomains"
    "WWW-Authenticate"              => "Bearer authorization_uri=https://login.windows.net/952e47c4-05de-4282-83af-5f4b46b1628f, Basic realm=\"https://pkgsprodsu3weu.app.pkgs.visualstudio.com/\", TFS-Federated"
    "X-Cache"                       => "CONFIG_NOCACHE"
    "X-Content-Type-Options"        => "nosniff"
    "X-FRAME-OPTIONS"               => "SAMEORIGIN"
    "X-MSEdge-Ref"                  => "Ref A: 129F9B74C5E449BEB06ABF978E44991D Ref B: AMS04EDGE2318 Ref C: 2024-08-15T15:13:35Z"
    "X-TFS-FedAuthIssuer"           => "https://www.visualstudio.com/"
    "X-TFS-FedAuthRealm"            => "https://pkgsprodsu3weu.app.pkgs.visualstudio.com/"
    "X-TFS-FedAuthRedirect"         => "https://spsprodweu2.vssps.visualstudio.com/_signin?realm=pkgs.dev.azure.com&reply_to=https%3A%2F%2Fpkgs.dev.azure.com%2FORG%2F_packaging%2FPROJ%2Fnpm%2Fregistry%2F%40uol%2Fcwd&redirect=1&hid=4ca4e53e-dfba-4ff5-ad16-05379cc4a641&context=eyJodCI6MiwiaGlkIjoiNjBhMWQ5N2UtNGUyMS00ZGJmLWJjNDYtMmRkNGUzYTIzNjMyIiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ud2luZG93cy5uZXQiXX01"
    "X-TFS-ProcessId"               => "c5f1614e-b4b0-4f2b-86c2-6f4e0926849f"
    "X-TFS-Session"                 => "9b826497-9b78-4803-b226-531875e06122"
    "X-VSS-AuthorizationEndpoint"   => "https://vssps.dev.azure.com/ORG/"
    "X-VSS-E2EID"                   => "9b826497-9b78-4803-b226-531875e06122"
    "X-VSS-ResourceTenant"          => "952e47c4-05de-4282-83af-5f4b46b1628f"
    "X-VSS-S2STargetService"        => "00000030-0000-8888-8000-000000000000/visualstudio.com"
    "X-VSS-SenderDeploymentId"      => "1a640fd9-ac39-bf02-92ac-d7705ca2547a"
  }
  :host              => "pkgs.dev.azure.com"
  :local_address     => "172.17.0.2"
  :local_port        => 51772
  :method            => :get
  :omit_default_port => true
  :path              => "/ORG/_packaging/PROJ/npm/registry/@uol%2Fcwd"
  :port              => 443
  :query             => nil
  :reason_phrase     => "Unauthorized"
  :remote_ip         => "13.107.42.20"
  :scheme            => "https"
  :status            => 401
  :status_line       => "HTTP/1.1 401 Unauthorized\r\n"
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-npm_and_yarn-0.267.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:338:in `check_npm_response': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): pkgs.dev.azure.com/UoLIct/_packaging/Packages/npm/registry (Dependabot::PrivateSourceAuthenticationFailure)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-npm_and_yarn-0.267.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:297:in `fetch_npm_details'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-npm_and_yarn-0.267.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:291:in `npm_details'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-npm_and_yarn-0.267.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:118:in `valid_npm_details?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-npm_and_yarn-0.267.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:41:in `latest_version_from_registry'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-npm_and_yarn-0.267.0/lib/dependabot/npm_and_yarn/update_checker.rb:303:in `latest_released_version'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-npm_and_yarn-0.267.0/lib/dependabot/npm_and_yarn/update_checker.rb:311:in `latest_version_details'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-npm_and_yarn-0.267.0/lib/dependabot/npm_and_yarn/update_checker.rb:42:in `latest_version'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.267.0/lib/dependabot/update_checkers/base.rb:314:in `numeric_version_up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation_2_7.rb:919:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation_2_7.rb:919:in `block in create_validator_method_medium0'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.267.0/lib/dependabot/update_checkers/base.rb:267:in `version_up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation_2_7.rb:919:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation_2_7.rb:919:in `block in create_validator_method_medium0'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.267.0/lib/dependabot/update_checkers/base.rb:82:in `up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation_2_7.rb:919:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11495/lib/types/private/methods/call_validation_2_7.rb:919:in `block in create_validator_method_medium0'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-npm_and_yarn-0.267.0/lib/dependabot/npm_and_yarn/update_checker.rb:30:in `up_to_date?'
	from bin/update_script.rb:598:in `block in <main>'
	from bin/update_script.rb:561:in `each'
	from bin/update_script.rb:561:in `<main>'

```

@mburumaxwell @rhyskoedijk I'm guessing this is a Dependabot Core  issue?

**Comment by rhyskoedijk** [comment]
> I'm guessing this is a Dependabot Core issue?

Yes and no. See: https://github.com/tinglesoftware/dependabot-azure-devops/issues/685#issuecomment-2295420972

**Comment by cherealnice** [comment]
> @cherealnice Did you manage to resolve your NPM issue? I'm running into the exact same issue and whatever I try does not resolve it.

No I gave up a while ago. Tried the debug header with the same result :/

**Comment by eli-gc** [comment]
Anyone have any luck on this? Getting this as well after upgrading to Yarn Berry no matter what I try.

**Comment by rhyskoedijk** [comment]
@eli-gc please see [unsupported features and configurations](https://github.com/tinglesoftware/dependabot-azure-devops?tab=readme-ov-file#extension-task). 

There are several known authentication issues when using Task V1; If possible, [migrate to Task V2](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/docs/migrations/v1-to-v2.md#summary-of-changes-v1--v2); If you are already using Task V2, please log an issue with a copy of your configuration and logs so we can investigate.
