### ISSUE TITLE
extraEnvironmentVariables settings are not passed to docker

### ISSUE THREAD

**Issue by asparrowhawk** [tinglesoftware/dependabot-azure-devops#160]
It appears there is an issue with passing additional environment variables to the dependabot docker image using Microsoft Azure Pipelines.

Using the following setting values in the yaml file:

```yaml
- task: dependabot@1
  inputs:
    packageManager: 'nuget'
    extraEnvironmentVariables: "EXCON_DEBUG=1;A=B"
    targetBranch: master
```

I am seeing the following in the Azure DevOps pipeline output

```
Starting: dependabot
==============================================================================
Task         : Dependabot
Description  : Automatically update dependencies and vulnerabilities in your code
Version      : 1.5.132
Author       : Tingle Software
Help         : For help please visit https://github.com/tinglesoftware/dependabot-azure-devops
==============================================================================

##[debug]milestone=undefined
##[debug]extraEnvironmentVariables=EXCON_DEBUG=1;A=B
##[debug]which 'docker'
##[debug]found: '/usr/bin/docker'
##[debug]which '/usr/bin/docker'

##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5"]
##[debug]/usr/bin/docker arg: ["-e","AZURE_AUTO_APPROVE_PR=false"]
##[debug]/usr/bin/docker arg: ["-e","0="]
##[debug]/usr/bin/docker arg: ["-e","1="]
##[debug]Running docker container -> 'tingle/dependabot-azure-devops:0.5' ...
```

So it appears that the `extraEnvironmentVariables` setting value is not being correctly passed to docker run.

I had a quick look at PR #139 and the code changes seem to be OK, But as you can see the result is different and "0=" and "1=" appear instead of `EXCON_DEBUG` and `A`.

**Comment by mburumaxwell** [comment]
@asparrowhawk Please share the debug output for Azure Pipelines showing the results of the `getDelimitedInput(...)` function call and surrounding outputs.

**Comment by asparrowhawk** [comment]
@mburumaxwell This is the full output from the Azure DevOps pipeline:

```
2021-07-27T18:46:42.7813505Z ##[debug]Evaluating condition for step: 'dependabot'
2021-07-27T18:46:42.7814541Z ##[debug]Evaluating: SucceededNode()
2021-07-27T18:46:42.7814934Z ##[debug]Evaluating SucceededNode:
2021-07-27T18:46:42.7815399Z ##[debug]=> True
2021-07-27T18:46:42.7815765Z ##[debug]Result: True
2021-07-27T18:46:42.7816269Z ##[section]Starting: dependabot
2021-07-27T18:46:42.7829057Z ==============================================================================
2021-07-27T18:46:42.7829388Z Task         : Dependabot
2021-07-27T18:46:42.7829694Z Description  : Automatically update dependencies and vulnerabilities in your code
2021-07-27T18:46:42.7829975Z Version      : 1.5.132
2021-07-27T18:46:42.7830209Z Author       : Tingle Software
2021-07-27T18:46:42.7830564Z Help         : For help please visit https://github.com/tinglesoftware/dependabot-azure-devops
2021-07-27T18:46:42.7830956Z ==============================================================================
2021-07-27T18:46:42.7916433Z ##[debug]Using node path: /home/vsts/agents/2.189.0/externals/node10/bin/node
2021-07-27T18:46:42.9324463Z ##[debug]agent.TempDirectory=/home/vsts/work/_temp
2021-07-27T18:46:42.9352088Z ##[debug]loading inputs and endpoints
2021-07-27T18:46:42.9362121Z ##[debug]loading INPUT_USECONFIGFILE
2021-07-27T18:46:42.9378844Z ##[debug]loading INPUT_PACKAGEMANAGER
2021-07-27T18:46:42.9383124Z ##[debug]loading INPUT_TARGETBRANCH
2021-07-27T18:46:42.9386344Z ##[debug]loading INPUT_OPENPULLREQUESTSLIMIT
2021-07-27T18:46:42.9389511Z ##[debug]loading INPUT_VERSIONINGSTRATEGY
2021-07-27T18:46:42.9392516Z ##[debug]loading INPUT_FAILONEXCEPTION
2021-07-27T18:46:42.9395597Z ##[debug]loading INPUT_SETAUTOCOMPLETE
2021-07-27T18:46:42.9398516Z ##[debug]loading INPUT_AUTOAPPROVE
2021-07-27T18:46:42.9401529Z ##[debug]loading INPUT_AZUREDEVOPSACCESSTOKEN
2021-07-27T18:46:42.9404494Z ##[debug]loading INPUT_DOCKERIMAGETAG
2021-07-27T18:46:42.9407333Z ##[debug]loading INPUT_EXTRAENVIRONMENTVARIABLES
2021-07-27T18:46:42.9410765Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2021-07-27T18:46:42.9413942Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2021-07-27T18:46:42.9417002Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2021-07-27T18:46:42.9422939Z ##[debug]loading SECRET_PAT
2021-07-27T18:46:42.9426390Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2021-07-27T18:46:42.9429616Z ##[debug]loaded 16
2021-07-27T18:46:42.9436174Z ##[debug]Agent.ProxyUrl=undefined
2021-07-27T18:46:42.9439249Z ##[debug]Agent.CAInfo=undefined
2021-07-27T18:46:42.9441208Z ##[debug]Agent.ClientCert=undefined
2021-07-27T18:46:42.9443085Z ##[debug]Agent.SkipCertValidation=undefined
2021-07-27T18:46:42.9706976Z ##[debug]Checking for docker install ...
2021-07-27T18:46:42.9713722Z ##[debug]which 'docker'
2021-07-27T18:46:42.9729781Z ##[debug]found: '/usr/bin/docker'
2021-07-27T18:46:42.9732050Z ##[debug]System.TeamFoundationCollectionUri=https://dev.azure.com/sparrowhawksoftware/
2021-07-27T18:46:42.9771704Z ##[debug]System.TeamProject=tipstarter-algorithm
2021-07-27T18:46:42.9781069Z ##[debug]setAutoComplete=false
2021-07-27T18:46:42.9784502Z ##[debug]failOnException=true
2021-07-27T18:46:42.9786478Z ##[debug]excludeRequirementsToUnlock=undefined
2021-07-27T18:46:42.9789405Z ##[debug]autoApprove=false
2021-07-27T18:46:42.9791284Z ##[debug]autoApproveUserEmail=undefined
2021-07-27T18:46:42.9794451Z ##[debug]autoApproveUserToken=undefined
2021-07-27T18:46:42.9796496Z ##[debug]DEPENDABOT_EXTRA_CREDENTIALS=undefined
2021-07-27T18:46:42.9799413Z ##[debug]dockerImageTag=0.5
2021-07-27T18:46:42.9801239Z ##[debug]gitHubAccessToken=undefined
2021-07-27T18:46:42.9803012Z ##[debug]gitHubConnection=undefined
2021-07-27T18:46:42.9805961Z ##[debug]azureDevOpsAccessToken=***
2021-07-27T18:46:42.9807815Z ##[debug]targetRepositoryName=undefined
2021-07-27T18:46:42.9809829Z ##[debug]No custom repository provided. The Pipeline Repository Name shall be used.
2021-07-27T18:46:42.9812957Z ##[debug]Build.Repository.Name=tipstarter-algorithm
2021-07-27T18:46:42.9814934Z ##[debug]DEPENDABOT_ALLOW_CONDITIONS=undefined
2021-07-27T18:46:42.9817097Z ##[debug]DEPENDABOT_IGNORE_CONDITIONS=undefined
2021-07-27T18:46:42.9819991Z ##[debug]useConfigFile=false
2021-07-27T18:46:42.9823791Z ##[debug]packageManager=nuget
2021-07-27T18:46:42.9825742Z ##[debug]directory=undefined
2021-07-27T18:46:42.9828555Z ##[debug]openPullRequestsLimit=5
2021-07-27T18:46:42.9831318Z ##[debug]targetBranch=master
2021-07-27T18:46:42.9833981Z ##[debug]versioningStrategy=auto
2021-07-27T18:46:42.9835857Z ##[debug]milestone=undefined
2021-07-27T18:46:42.9839465Z ##[debug]extraEnvironmentVariables=EXCON_DEBUG=1
2021-07-27T18:46:42.9842864Z ##[debug]which 'docker'
2021-07-27T18:46:42.9848522Z ##[debug]found: '/usr/bin/docker'
2021-07-27T18:46:42.9852376Z ##[debug]which '/usr/bin/docker'
2021-07-27T18:46:42.9854895Z ##[debug]found: '/usr/bin/docker'
2021-07-27T18:46:42.9858360Z ##[debug]/usr/bin/docker arg: ["run"]
2021-07-27T18:46:42.9860686Z ##[debug]/usr/bin/docker arg: ["--rm"]
2021-07-27T18:46:42.9862894Z ##[debug]/usr/bin/docker arg: ["-i"]
2021-07-27T18:46:42.9865401Z ##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_PACKAGE_MANAGER=nuget"]
2021-07-27T18:46:42.9868416Z ##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_FAIL_ON_EXCEPTION=true"]
2021-07-27T18:46:42.9870847Z ##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_EXCLUDE_REQUIREMENTS_TO_UNLOCK="]
2021-07-27T18:46:42.9873216Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_PROTOCOL=https"]
2021-07-27T18:46:42.9875583Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_HOSTNAME=dev.azure.com"]
2021-07-27T18:46:42.9877933Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_ORGANIZATION=sparrowhawksoftware"]
2021-07-27T18:46:42.9880261Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_PROJECT=tipstarter-algorithm"]
2021-07-27T18:46:42.9882534Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_REPOSITORY=tipstarter-algorithm"]
2021-07-27T18:46:42.9884968Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_ACCESS_TOKEN=***"]
2021-07-27T18:46:42.9924816Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_SET_AUTO_COMPLETE=false"]
2021-07-27T18:46:42.9925708Z ##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_TARGET_BRANCH=master"]
2021-07-27T18:46:42.9926449Z ##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_VERSIONING_STRATEGY=auto"]
2021-07-27T18:46:42.9927160Z ##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5"]
2021-07-27T18:46:42.9927868Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_AUTO_APPROVE_PR=false"]
2021-07-27T18:46:42.9928807Z ##[debug]/usr/bin/docker arg: ["-e","0="]
2021-07-27T18:46:42.9929497Z ##[debug]Running docker container -> 'tingle/dependabot-azure-devops:0.5' ...
2021-07-27T18:46:42.9930227Z ##[debug]/usr/bin/docker arg: ["tingle/dependabot-azure-devops:0.5"]
2021-07-27T18:46:42.9930798Z ##[debug]exec tool: /usr/bin/docker
2021-07-27T18:46:42.9931258Z ##[debug]arguments:
2021-07-27T18:46:42.9931695Z ##[debug]   run
2021-07-27T18:46:42.9932211Z ##[debug]   --rm
2021-07-27T18:46:42.9932731Z ##[debug]   -i
2021-07-27T18:46:42.9933228Z ##[debug]   -e
2021-07-27T18:46:42.9933700Z ##[debug]   DEPENDABOT_PACKAGE_MANAGER=nuget
2021-07-27T18:46:42.9934266Z ##[debug]   -e
2021-07-27T18:46:42.9934739Z ##[debug]   DEPENDABOT_FAIL_ON_EXCEPTION=true
2021-07-27T18:46:42.9935292Z ##[debug]   -e
2021-07-27T18:46:42.9935765Z ##[debug]   DEPENDABOT_EXCLUDE_REQUIREMENTS_TO_UNLOCK=
2021-07-27T18:46:42.9936333Z ##[debug]   -e
2021-07-27T18:46:42.9936787Z ##[debug]   AZURE_PROTOCOL=https
2021-07-27T18:46:42.9937321Z ##[debug]   -e
2021-07-27T18:46:42.9937771Z ##[debug]   AZURE_HOSTNAME=dev.azure.com
2021-07-27T18:46:42.9938318Z ##[debug]   -e
2021-07-27T18:46:42.9938799Z ##[debug]   AZURE_ORGANIZATION=sparrowhawksoftware
2021-07-27T18:46:42.9939361Z ##[debug]   -e
2021-07-27T18:46:42.9939925Z ##[debug]   AZURE_PROJECT=tipstarter-algorithm
2021-07-27T18:46:42.9940502Z ##[debug]   -e
2021-07-27T18:46:42.9941083Z ##[debug]   AZURE_REPOSITORY=tipstarter-algorithm
2021-07-27T18:46:42.9941652Z ##[debug]   -e
2021-07-27T18:46:42.9942297Z ##[debug]   AZURE_ACCESS_TOKEN=***
2021-07-27T18:46:42.9942850Z ##[debug]   -e
2021-07-27T18:46:42.9943517Z ##[debug]   AZURE_SET_AUTO_COMPLETE=false
2021-07-27T18:46:42.9944085Z ##[debug]   -e
2021-07-27T18:46:42.9944555Z ##[debug]   DEPENDABOT_TARGET_BRANCH=master
2021-07-27T18:46:42.9945103Z ##[debug]   -e
2021-07-27T18:46:42.9945563Z ##[debug]   DEPENDABOT_VERSIONING_STRATEGY=auto
2021-07-27T18:46:42.9946119Z ##[debug]   -e
2021-07-27T18:46:42.9946599Z ##[debug]   DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5
2021-07-27T18:46:42.9947157Z ##[debug]   -e
2021-07-27T18:46:42.9947618Z ##[debug]   AZURE_AUTO_APPROVE_PR=false
2021-07-27T18:46:42.9948144Z ##[debug]   -e
2021-07-27T18:46:42.9948568Z ##[debug]   0=
2021-07-27T18:46:42.9949135Z ##[debug]   tingle/dependabot-azure-devops:0.5
2021-07-27T18:46:42.9951555Z [command]/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=nuget -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e DEPENDABOT_EXCLUDE_REQUIREMENTS_TO_UNLOCK= -e AZURE_PROTOCOL=https -e AZURE_HOSTNAME=dev.azure.com -e AZURE_ORGANIZATION=sparrowhawksoftware -e AZURE_PROJECT=tipstarter-algorithm -e AZURE_REPOSITORY=tipstarter-algorithm -e AZURE_ACCESS_TOKEN=*** -e AZURE_SET_AUTO_COMPLETE=false -e DEPENDABOT_TARGET_BRANCH=master -e DEPENDABOT_VERSIONING_STRATEGY=auto -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5 -e AZURE_AUTO_APPROVE_PR=false -e 0= tingle/dependabot-azure-devops:0.5
2021-07-27T18:46:45.2773061Z warning: parser/current is loading parser/ruby27, which recognizes
2021-07-27T18:46:45.2774787Z warning: 2.7.4-compliant syntax, but you are running 2.7.1.
2021-07-27T18:46:45.2775985Z warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
2021-07-27T18:46:54.2918710Z ./update-script.rb:440:in `block in <main>': Pull Request creation failed with status 400. Message: TF401398: The pull request cannot be activated because the source and/or the target branch no longer exists, or the requested refs are not branches (StandardError)
2021-07-27T18:46:54.2932558Z 	from ./update-script.rb:272:in `each'
2021-07-27T18:46:54.2934077Z 	from ./update-script.rb:272:in `<main>'
2021-07-27T18:46:54.3053366Z Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
2021-07-27T18:46:54.3054139Z Using 'https://dev.azure.com:443/' as API endpoint
2021-07-27T18:46:54.3054841Z Fetching nuget dependency files for sparrowhawksoftware/tipstarter-algorithm/_git/tipstarter-algorithm
2021-07-27T18:46:54.3055470Z Targeting 'master' branch under '/' directory
2021-07-27T18:46:54.3055984Z Using 'auto' requirements update strategy
2021-07-27T18:46:54.3056315Z Parsing dependencies information
2021-07-27T18:46:54.3056651Z Checking if AutoMapper 10.1.1 needs updating
2021-07-27T18:46:54.3056982Z No update needed for AutoMapper 10.1.1
2021-07-27T18:46:54.3057324Z Checking if CsvHelper 27.1.1 needs updating
2021-07-27T18:46:54.3057650Z No update needed for CsvHelper 27.1.1
2021-07-27T18:46:54.3057999Z Checking if FluentAssertions 5.10.3 needs updating
2021-07-27T18:46:54.3058347Z No update needed for FluentAssertions 5.10.3
2021-07-27T18:46:54.3058703Z Checking if Microsoft.NET.Test.Sdk 16.10.0 needs updating
2021-07-27T18:46:54.3059098Z No update needed for Microsoft.NET.Test.Sdk 16.10.0
2021-07-27T18:46:54.3059447Z Checking if morelinq 3.3.2 needs updating
2021-07-27T18:46:54.3059784Z No update needed for morelinq 3.3.2
2021-07-27T18:46:54.3060099Z Checking if xunit 2.4.1 needs updating
2021-07-27T18:46:54.3060424Z No update needed for xunit 2.4.1
2021-07-27T18:46:54.3060766Z Checking if xunit.runner.visualstudio 2.4.3 needs updating
2021-07-27T18:46:54.3061137Z No update needed for xunit.runner.visualstudio 2.4.3
2021-07-27T18:46:54.3068443Z Checking if coverlet.collector 3.1.0 needs updating
2021-07-27T18:46:54.3068994Z No update needed for coverlet.collector 3.1.0
2021-07-27T18:46:54.3069372Z Checking if Microsoft.ApplicationInsights 2.17.0 needs updating
2021-07-27T18:46:54.3069744Z No update needed for Microsoft.ApplicationInsights 2.17.0
2021-07-27T18:46:54.3070161Z Checking if Microsoft.Azure.Functions.Worker.Extensions.Http 3.0.13 needs updating
2021-07-27T18:46:54.3070589Z No update needed for Microsoft.Azure.Functions.Worker.Extensions.Http 3.0.13
2021-07-27T18:46:54.3071324Z Checking if Microsoft.Azure.Functions.Worker.Extensions.Storage 4.0.4 needs updating
2021-07-27T18:46:54.3071757Z No update needed for Microsoft.Azure.Functions.Worker.Extensions.Storage 4.0.4
2021-07-27T18:46:54.3072169Z Checking if Microsoft.Azure.Functions.Worker.Sdk 1.0.3 needs updating
2021-07-27T18:46:54.3072518Z Requirements to unlock own
2021-07-27T18:46:54.3072844Z Updating Microsoft.Azure.Functions.Worker.Sdk from 1.0.3 to 1.0.4
2021-07-27T18:46:54.3073338Z Submitting Microsoft.Azure.Functions.Worker.Sdk pull request for creation. Failed! PR already exists or an error has occurred.
2021-07-27T18:46:54.4715912Z ##[debug]Exit code 1 received from tool '/usr/bin/docker'
2021-07-27T18:46:54.4726145Z ##[debug]STDIO streams have closed for tool '/usr/bin/docker'
2021-07-27T18:46:54.4762118Z ##[debug]task result: Failed
2021-07-27T18:46:54.4794046Z ##[error]The process '/usr/bin/docker' failed with exit code 1
2021-07-27T18:46:54.4804215Z ##[debug]Processed: ##vso[task.issue type=error;]The process '/usr/bin/docker' failed with exit code 1
2021-07-27T18:46:54.4806855Z ##[debug]Processed: ##vso[task.complete result=Failed;]The process '/usr/bin/docker' failed with exit code 1
2021-07-27T18:46:54.4839787Z ##[section]Finishing: dependabot
```
