### ISSUE TITLE
Error scanning jruby repo (bundler / Gemfile): `check_update_strategy': Unknown update strategy: auto (RuntimeError)

### ISSUE THREAD

**Issue by pritish-kapoor** [tinglesoftware/dependabot-azure-devops#212]
Thanks for creating this very useful extension!

We're trying to scan some jruby repos but it keeps failing with this error:
```
==============================================================================
Task         : Dependabot
Version      : 1.5.164
==============================================================================
/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=bundler -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e DEPENDABOT_EXCLUDE_REQUIREMENTS_TO_UNLOCK= -e AZURE_PROTOCOL=https -e AZURE_HOSTNAME=dev.azure.com -e AZURE_ORGANIZATION=my-org -e AZURE_PROJECT=my-proj -e AZURE_REPOSITORY=my-repo -e AZURE_ACCESS_TOKEN=*** -e AZURE_SET_AUTO_COMPLETE=false -e DEPENDABOT_DIRECTORY=/ -e DEPENDABOT_TARGET_BRANCH=jruby -e DEPENDABOT_VERSIONING_STRATEGY=auto -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=100 -e GITHUB_ACCESS_TOKEN=*** -e AZURE_AUTO_APPROVE_PR=false tingle/dependabot-azure-devops:0.5
......
GitHub access token has been provided.
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using 'https://dev.azure.com:443/' as API endpoint
Fetching bundler dependency files for my-org/my-proj/_git/my-repo
Targeting 'jruby' branch under '/' directory
Using 'auto' requirements update strategy
Parsing dependencies information
Checking if puma 3.10.0 needs updating
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-bundler-0.169.3/lib/dependabot/bundler/update_checker/requirements_updater.rb:50:in `check_update_strategy': Unknown update strategy: auto (RuntimeError)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-bundler-0.169.3/lib/dependabot/bundler/update_checker/requirements_updater.rb:21:in `initialize'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-bundler-0.169.3/lib/dependabot/bundler/update_checker.rb:77:in `new'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-bundler-0.169.3/lib/dependabot/bundler/update_checker.rb:77:in `updated_requirements'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.169.3/lib/dependabot/update_checkers/base.rb:266:in `preferred_version_resolvable_with_unlock?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.169.3/lib/dependabot/update_checkers/base.rb:249:in `numeric_version_can_update?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.169.3/lib/dependabot/update_checkers/base.rb:199:in `version_can_update?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.169.3/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
	from ./update-script.rb:304:in `block in <main>'
	from ./update-script.rb:272:in `each'
	from ./update-script.rb:272:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1
```

As per [this](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#versioning-strategy) document, `auto` `versioning-strategy` is supported with `bundler`. We are unable to figure out what we're doing wrong. For maven, gradle, go, etc., it is working well for us.

Gemfile:
```
source 'https://rubygems.org'

gem 'puma'
gem 'json'

# Using 1.6.7.2 because when we tried a later version (1.8+) we were unable to parse the factor metadata without
# blowing up our heap.
gem 'nokogiri', '1.6.7.2'
gem 'jdbc-sqlite3'
gem 'sequel'
gem 'rack'
gem 'sinatra'
gem 'uuid'
gem 'macaddr'
gem 'rest-client'
gem 'omniauth'
gem 'omniauth-saml'
gem 'ruby-saml'
gem 'httparty'
gem 'activesupport'
gem 'json-jwt'
gem 'jwt'
gem 'moneta'
```

Gemfile.lock:
```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (5.1.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    bindata (2.4.1)
    concurrent-ruby (1.0.5-java)
    domain_name (0.5.20170404)
      unf (>= 0.0.5, < 1.0.0)
    hashie (3.5.6)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    httparty (0.15.6)
      multi_xml (>= 0.5.2)
    i18n (0.8.6)
    jdbc-sqlite3 (3.15.1)
    json (2.1.0-java)
    json-jwt (1.7.2)
      activesupport
      bindata
      multi_json (>= 1.3)
      securecompare
      url_safe_base64
    jwt (2.0.0)
    macaddr (1.7.1)
      systemu (~> 2.6.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    minitest (5.10.3)
    moneta (1.0.0)
    multi_json (1.12.2)
    multi_xml (0.6.0)
    mustermann (1.0.1)
    netrc (0.11.0)
    nokogiri (1.6.7.2-java)
    omniauth (1.6.1)
      hashie (>= 3.4.6, < 3.6.0)
      rack (>= 1.6.2, < 3)
    omniauth-saml (1.8.1)
      omniauth (~> 1.3)
      ruby-saml (~> 1.4, >= 1.4.3)
    puma (3.10.0-java)
    rack (2.0.3)
    rack-protection (2.0.0)
      rack
    rest-client (2.0.2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    ruby-saml (1.5.0)
      nokogiri (>= 1.5.10)
    securecompare (1.0.0)
    sequel (5.0.0)
    sinatra (2.0.0)
      mustermann (~> 1.0)
      rack (~> 2.0)
      rack-protection (= 2.0.0)
      tilt (~> 2.0)
    systemu (2.6.5)
    thread_safe (0.3.6-java)
    tilt (2.0.8)
    tzinfo (1.2.3)
      thread_safe (~> 0.1)
    unf (0.1.4-java)
    url_safe_base64 (0.2.2)
    uuid (2.3.8)
      macaddr (~> 1.0)

PLATFORMS
  java

DEPENDENCIES
  activesupport
  httparty
  jdbc-sqlite3
  json
  json-jwt
  jwt
  macaddr
  moneta
  nokogiri (= 1.6.7.2)
  omniauth
  omniauth-saml
  puma
  rack
  rest-client
  ruby-saml
  sequel
  sinatra
  uuid

BUNDLED WITH
   1.15.4
```

**Comment by mburumaxwell** [comment]
@rampa-necessity what happens if you do not specify the versioning strategy?
