### ISSUE TITLE
Error running Dependabot: Unexpected '@' after '[#<Nokogiri ...

### ISSUE THREAD

**Issue by Deltids** [tinglesoftware/dependabot-azure-devops#231]
I'll appreciate any input on this one :)

Configuration:
```
trigger: none # Disable CI trigger

schedules:
- cron: '0 2 * * *' # daily at 2am UTC
  always: true # run even when there are no code changes
  branches:
    include:
      - master
  batch: true
  displayName: Daily

pool:
  vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)

steps:
- task: dependabot@1
  inputs:
    packageManager: 'nuget'
    openPullRequestsLimit: 1
    azureDevOpsAccessToken: $(pat)
```

Error Message:
```
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/css/parser_extras.rb:84:in `on_error': unexpected '@' after '[#<Nokogiri::CSS::Node:0x0000557691490d60 @type=:CHILD_SELECTOR, @value=[#<Nokogiri::CSS::Node:0x0000557691491670 @type=:ELEMENT_NAME, @value=["configuration"]>, #<Nokogiri::CSS::Node:0x0000557691490e28 @type=:CHILD_SELECTOR, @value=[#<Nokogiri::CSS::Node:0x0000557691491288 @type=:ELEMENT_NAME, @value=["packageSourceCredentials"]>, #<Nokogiri::CSS::Node:0x0000557691490f90 @type=:ELEMENT_NAME, @value=["MYORG"]>]>]>]' (Nokogiri::CSS::SyntaxError)
	from (eval):3:in `_racc_do_parse_c'
	from (eval):3:in `do_parse'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/css/parser_extras.rb:66:in `parse'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/css/parser_extras.rb:76:in `xpath_for'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/css.rb:46:in `xpath_for'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/xml/searchable.rb:246:in `block in xpath_query_from_css_rule'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/xml/searchable.rb:245:in `map'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/xml/searchable.rb:245:in `xpath_query_from_css_rule'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/xml/searchable.rb:237:in `block in css_rules_to_xpath'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/xml/searchable.rb:237:in `map'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/xml/searchable.rb:237:in `css_rules_to_xpath'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/xml/searchable.rb:206:in `css_internal'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/nokogiri-1.13.1-x86_64-linux/lib/nokogiri/xml/searchable.rb:129:in `css'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/repository_finder.rb:228:in `block in add_config_file_credentials'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/repository_finder.rb:222:in `each'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/repository_finder.rb:222:in `add_config_file_credentials'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/repository_finder.rb:185:in `repos_from_config_file'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/repository_finder.rb:148:in `block in config_file_repositories'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/repository_finder.rb:148:in `each'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/repository_finder.rb:148:in `flat_map'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/repository_finder.rb:148:in `config_file_repositories'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/repository_finder.rb:133:in `known_repositories'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/repository_finder.rb:31:in `find_dependency_urls'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/repository_finder.rb:22:in `dependency_urls'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/version_finder.rb:302:in `dependency_urls'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/version_finder.rb:193:in `v3_nuget_listings'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/version_finder.rb:105:in `available_v3_versions'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/version_finder.rb:57:in `versions'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker/version_finder.rb:34:in `latest_version_details'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker.rb:87:in `latest_version_details'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker.rb:15:in `latest_version'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.171.4/lib/dependabot/update_checkers/base.rb:231:in `numeric_version_up_to_date?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.171.4/lib/dependabot/update_checkers/base.rb:189:in `version_up_to_date?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.171.4/lib/dependabot/update_checkers/base.rb:33:in `up_to_date?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.171.4/lib/dependabot/nuget/update_checker.rb:55:in `up_to_date?'
	from ./update-script.rb:294:in `block in <main>'
	from ./update-script.rb:272:in `each'
	from ./update-script.rb:272:in `<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using '[https://dev.azure.com:443/'](https://dev.azure.com/') as API endpoint
Fetching nuget dependency files for MYORG/MYPROJECT/_git/MYPROJECT
Targeting 'default' branch under '/' directory
Using 'auto' requirements update strategy
Parsing dependencies information
Checking if Castle.Core 4.4.1 needs updating
##[error]The process '/usr/bin/docker' failed with exit code 1
```

**Comment by Deltids** [comment]
Using the dependabot we set up before installing the extension, I got the same error message, but instead of '@' i got '@Release', so I think it is related to Artifacts Feed
https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops

cause our nuget.config is 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="MYORG@Release" value="https://pkgs.dev.azure.com/MYORG/_packaging/MYORG%40Local/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by mburumaxwell** [comment]
@Deltids to the best of my knowledge, views are a concept of Azure Artifacts supporting multiple package ecosystems (NuGet, npm, etc). According to the docs you have linked, views are used to control access and visibility. Since this is not present in NuGet as a spec/standard, it is not present in [dependabot-core](https://github.com/dependabot/dependabot-core). This extension builds up on the work done in that repository. However, I am inclined to believe that the PAT used for accessing the feed in `DEPENDABOT_EXTRA_CREDENTIALS` may be used to control which packages become available.
