### ISSUE TITLE
Maven: pom not found?

### ISSUE THREAD

**Issue by cpolzer** [tinglesoftware/dependabot-azure-devops#262]
Hello,

I am evaluaing the dependabot azure devops extension in a simple maven based project.

The step is configured like this:

```
  - task: dependabot@1
    inputs:
      packageManager: 'maven'
      targetBranch: 'main'
      versioningStrategy: 'auto' 
```

It seems the pom xml file is not found:

```
Status: Downloaded newer image for tingle/dependabot-azure-devops:0.5
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:151:in `rescue in fetch_file_from_host': Dependabot::DependencyFileNotFound (Dependabot::DependencyFileNotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:136:in `fetch_file_from_host'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-maven-0.180.1/lib/dependabot/maven/file_fetcher.rb:33:in `pom'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-maven-0.180.1/lib/dependabot/maven/file_fetcher.rb:25:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./update-script.rb:245:in `<main>'
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/clients/azure.rb:239:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/clients/azure.rb:101:in `fetch_file_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:420:in `_fetch_file_content_fully_specified'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:399:in `_fetch_file_content'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:140:in `fetch_file_from_host'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-maven-0.180.1/lib/dependabot/maven/file_fetcher.rb:33:in `pom'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-maven-0.180.1/lib/dependabot/maven/file_fetcher.rb:25:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./update-script.rb:245:in `<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using '[https://dev.azure.com:443/'](https://dev.azure.com/') as API endpoint
Fetching maven dependency files for schwarzit/schwarzit.odj.dlvrddd/_git/appcloud-spring-demo
Targeting 'default' branch under '/' directory
```

Any hints really appreciated & I am happy to provide more informations if needed.

**Comment by mburumaxwell** [comment]
@cpolzer could you share your repository folder structure?
