### ISSUE TITLE
Dependabot does not parse https_url with username and password in it

### ISSUE THREAD

**Issue by cliftonz1** [tinglesoftware/dependabot-azure-devops#263]
We are trailing dependabot in our on-prem ADO system. However, when dependabot tries to connect we get this error:
```
[](http://user:password@proxypool:9119"/)from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/clients/azure.rb:222:in `block in get'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/clients/azure.rb:286:in `retry_connection_failures'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/clients/azure.rb:221:in `get'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/clients/azure.rb:52:in `fetch_commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:73:in `commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:386:in `_full_specification_for'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:176:in `_fetch_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:163:in `repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.180.1/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.180.1/lib/dependabot/nuget/file_fetcher.rb:55:in `project_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.180.1/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./update-script.rb:245:in `<main>'
```

**Comment by cliftonz1** [comment]
This is on a linux agent on-premise

**Comment by mburumaxwell** [comment]
@cliftonz1 this seems like a network problem, transient or otherwise. Have you asserted that the machine has internet connectivity to Azure DevOps? Maybe also add `EXCON_DEBUG=1` env for more information?

**Comment by cliftonz1** [comment]
Yes, we have asserted that the agent has access to Azure DevOps server and adding the EXCON_DEBUG  variable did not add any extra output.
It looks like the issue is in the ruby parser but I do not know if that is in this task or dependabot itself.
``` /usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67```

**Comment by mburumaxwell** [comment]
Indeed according to the stack trace, the error happens in the [parent repository](https://github.com/dependabot/dependabot-core).

However, one has to check if this is a result of values supplied by the task.

What is the username and password meant to access? Is it a repository or a private feed? Could you share how the task is configured? More logs will surely help. And..... you can exclude sensitive details.
