### ISSUE TITLE
latest version gives: undefined method `repo' for nil:NilClass

### ISSUE THREAD

**Issue by OneCyrus** [tinglesoftware/dependabot-azure-devops#273]
our weekly automated dependabot pipelines started to give the following error this weekend. No PRs are created anymore.

```
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.182.0/lib/dependabot/nuget/metadata_finder.rb:64:in `block in extract_source_repo': undefined method `repo' for nil:NilClass (NoMethodError)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.182.0/lib/dependabot/nuget/metadata_finder.rb:59:in `each'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.182.0/lib/dependabot/nuget/metadata_finder.rb:59:in `extract_source_repo'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.182.0/lib/dependabot/nuget/metadata_finder.rb:48:in `src_repo_from_project'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.182.0/lib/dependabot/nuget/metadata_finder.rb:21:in `look_up_source'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/metadata_finders/base.rb:123:in `source'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/metadata_finders/base.rb:25:in `source_url'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/pull_request_creator/message_builder.rb:357:in `source_url'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/pull_request_creator/message_builder.rb:282:in `block in dependency_links'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/pull_request_creator/message_builder.rb:281:in `map'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/pull_request_creator/message_builder.rb:281:in `dependency_links'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/pull_request_creator/message_builder.rb:203:in `version_commit_message_intro'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/pull_request_creator/message_builder.rb:129:in `commit_message_intro'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/pull_request_creator/message_builder.rb:55:in `commit_message'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/pull_request_creator.rb:172:in `azure_creator'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/pull_request_creator.rb:104:in `create'
	from ./update-script.rb:427:in `block in <main>'
	from ./update-script.rb:272:in `each'
	from ./update-script.rb:272:in `<main>'
```

**Comment by OneCyrus** [comment]
just verified with setting the docker image to 0.5.19. this works.

**Comment by mburumaxwell** [comment]
We had a similar problem a couple of days ago affecting a specific NuGet package then it disappeared. Still trying to get context as to the cause. Are you still facing this issue?

**Comment by OneCyrus** [comment]
still have the issue with the latest version. not sure if it's really a specific package. but it could be `SonarAnalyzer.CSharp`

**Comment by OneCyrus** [comment]
with 0.6.1 it works again. perfect!

looks like they reverted a PR related to nuget in the core. https://github.com/dependabot/dependabot-core/pull/5040
