### ISSUE TITLE
Bug in 0.6: undefined local variable or method `merge_strategy' for main:Object (NameError)

### ISSUE THREAD

**Issue by btastic** [tinglesoftware/dependabot-azure-devops#274]
Hey,

the whole error message looks like this:

```
./update-script.rb:475:in `block in <main>': undefined local variable or method `merge_strategy' for main:Object (NameError)
	from ./update-script.rb:273:in `each'
	from ./update-script.rb:273:in `<main>'
```

Apparently I forgot to initialise the variable here.

**Comment by btastic** [comment]
Thanks @mburumaxwell, it is working now!
