### ISSUE TITLE
/usr/bin/docker failed with exit code 1 - permissions of build service user set

### ISSUE THREAD

**Issue by piejanssens** [tinglesoftware/dependabot-azure-devops#324]
```
/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=docker -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e DEPENDABOT_EXCLUDE_REQUIREMENTS_TO_UNLOCK= -e AZURE_PROTOCOL=https -e AZURE_HOSTNAME=dev.azure.com -e AZURE_ORGANIZATION=PJ-ORG-e AZURE_PROJECT=project1 -e AZURE_REPOSITORY=app-ddk -e AZURE_ACCESS_TOKEN=*** -e AZURE_SET_AUTO_COMPLETE=false -e AZURE_MERGE_STRATEGY=2 -e DEPENDABOT_DIRECTORY=/docker -e DEPENDABOT_VERSIONING_STRATEGY=auto -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=10 -e AZURE_AUTO_APPROVE_PR=false tingle/dependabot-azure-devops:0.7
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-docker-0.196.0/lib/dependabot/docker/file_fetcher.rb:26:in `fetch_files': Dependabot::DependencyFileNotFound (Dependabot::DependencyFileNotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.196.0/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./update-script.rb:259:in `<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using '[https://dev.azure.com:443/'](https://dev.azure.com/') as API endpoint
Fetching docker dependency files for PJ-ORG/project1/_git/app-ddk-
Targeting 'default' branch under '/docker' directory
Using 'auto' requirements update strategy
##[debug]Exit code 1 received from tool '/usr/bin/docker'
##[debug]STDIO streams have closed for tool '/usr/bin/docker'
##[debug]task result: Failed
##[error]The process '/usr/bin/docker' failed with exit code 1
```

Project's build service user permissions are set like this:
<img width="626" alt="Screenshot 2022-08-08 at 17 36 46" src="https://user-images.githubusercontent.com/829098/183456781-e3fcaa1e-4aaa-42c7-bf81-02f49a6e804b.png">

By searching for similar issues I found that the permissions have to be set for the build service user, but this looks to be in order.

**Comment by sabareeshkkanan** [comment]
@piejanssens  how did you resolve this issue
