### ISSUE TITLE
'/usr/bin/docker' failed with exit code 1 without any useful info on trying to create PR

### ISSUE THREAD

**Issue by zidadrtl** [tinglesoftware/dependabot-azure-devops#374]
Hi,

I managed to set up the dependabot pipeline with private artifact feed based on the code in this issue here:
https://github.com/tinglesoftware/dependabot-azure-devops/issues/50

``` YAML

variables:
  - name: Repository
    value: "masstransit" 
    #value: ${{ replace(variables['Build.DefinitionName'],'Dependabot - ','') }} 
    # Important: Pipeline name must be "Dependabot - repository_name".

stages:
  - stage: CheckDependencies
    displayName: 'Check Dependencies'
    jobs:
      - job: Dependabot
        displayName: 'Dependabot'
        pool:
          # Only works with MacOS and Linux
          vmImage: 'ubuntu-latest' 
        steps:
          - checkout: 'git://Org Shared/${{ variables.Repository }}'

          # Creates $(VSS_NUGET_ACCESSTOKEN) for Private feeds
          - task: NuGetAuthenticate@1
            displayName: 'NuGet Private Feed Authentication'

          - task: dependabot@1
            displayName: 'Run Dependabot'
            inputs:
              useConfigFile: false
              packageManager: 'nuget'
              directory: '/'
              openPullRequestsLimit: '10'
              setAutoComplete: true
              mergeStrategy: '1'
              gitHubAccessToken: '$(Dependabot.GitHubAccessToken)'
              azureDevOpsAccessToken: '$(System.AccessToken)'
              targetRepositoryName: '${{ variables.Repository }}'
              extraEnvironmentVariables: DEPENDABOT_EXTRA_CREDENTIALS=[{"type":"nuget_feed","token":"$(VSS_NUGET_ACCESSTOKEN)","url":"https://pkgs.dev.azure.com/Org-nl/_packaging/Org.PackageFeed/nuget/v3/index.json"}]

```

But now I'm stuck at the part where it's trying to create a PR, and the docker log doesn't provide any useful information.
I gave full permissions to the "build agent user" and "build agent collection" for the project, but I still get this error:
 
```
2022-11-04T09:39:06.5767675Z [command]/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=nuget -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e DEPENDABOT_EXCLUDE_REQUIREMENTS_TO_UNLOCK= -e AZURE_PROTOCOL=https -e AZURE_HOSTNAME=dev.azure.com -e AZURE_ORGANIZATION=my-org -e AZURE_PROJECT=my-proj -e AZURE_REPOSITORY=messaging-masstransit -e AZURE_ACCESS_TOKEN=*** -e AZURE_SET_AUTO_COMPLETE=true -e AZURE_MERGE_STRATEGY=1 -e DEPENDABOT_DIRECTORY=/ -e DEPENDABOT_VERSIONING_STRATEGY=auto -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=10 -e GITHUB_ACCESS_TOKEN=$(Dependabot.GitHubAccessToken) -e AZURE_AUTO_APPROVE_PR=false -e DEPENDABOT_EXTRA_CREDENTIALS=[{"type":"nuget_feed","token":***,"url":"https://pkgs.dev.azure.com/my-org/_packaging/Org.PackageFeed/nuget/v3/index.json"}] tingle/dependabot-azure-devops:0.9
2022-11-04T09:39:06.8307017Z Unable to find image 'tingle/dependabot-azure-devops:0.9' locally
2022-11-04T09:39:08.3388223Z 0.9: Pulling from tingle/dependabot-azure-devops
...
2022-11-04T09:40:27.1887541Z 6b7bfb231103: Pull complete
2022-11-04T09:40:27.1980272Z Status: Downloaded newer image for tingle/dependabot-azure-devops:0.9
2022-11-04T09:40:39.7464355Z /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/octokit-5.4.0/lib/octokit/response/raise_error.rb:14:in `on_complete': GET https://api.github.com/repos/prometheus-net/prometheus-net/contents/: 401 - Bad credentials // See: https://docs.github.com/rest (Octokit::Unauthorized)
2022-11-04T09:40:39.7466667Z 	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/faraday-2.5.2/lib/faraday/middleware.rb:18:in `block in call'
...
2022-11-04T09:40:39.7518531Z 	from ./update-script.rb:310:in `<main>'
2022-11-04T09:40:39.7756876Z GitHub access token has been provided.
2022-11-04T09:40:39.7758290Z Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
2022-11-04T09:40:39.7759697Z Using 'https://dev.azure.com:443/' as API endpoint
2022-11-04T09:40:39.7760557Z Fetching nuget dependency files for my-org/my-proj/_git/messaging-masstransit
2022-11-04T09:40:39.7761205Z Targeting 'default' branch under '/' directory
2022-11-04T09:40:39.7761747Z Using 'auto' requirements update strategy
2022-11-04T09:40:39.7762123Z Parsing dependencies information
2022-11-04T09:40:39.7767109Z Checking if prometheus-net.AspNetCore 6.0.0 needs updating
2022-11-04T09:40:39.7767503Z Requirements to unlock own
2022-11-04T09:40:39.7768374Z Updating prometheus-net.AspNetCore from 6.0.0 to 7.0.0
2022-11-04T09:40:39.9838716Z ##[error]The process '/usr/bin/docker' failed with exit code 1
2022-11-04T09:40:39.9860911Z ##[section]Finishing: Run Dependabot
```

Do you have any clue what I'm missing?

**Comment by zidadrtl** [comment]
OK so the problem was that I specified a '$(Dependabot.GitHubAccessToken)' access token, I should have removed that part.
