### ISSUE TITLE
Error with auto-approve

### ISSUE THREAD

**Issue by Robin831** [tinglesoftware/dependabot-azure-devops#449]
We're getting an error during auto-approve, the PR is created though. It started after the 0.13 release.

```
Updating @babel/cli from 7.19.3 to 7.20.7
/home/dependabot/dependabot-script/azure_helpers.rb:92:in `pull_request_approve': undefined local variable or method `token' for #<Dependabot::Clients::Azure:0x00007fbd675dd370 @source=#<Dependabot::Source:0x00007fbd680db420 @provider="azure", @repo="***", @directory="/", @branch=nil, @commit=nil, @hostname="dev.azure.com", @api_endpoint="[https://dev.azure.com:443/">,](https://dev.azure.com/%22%3E,) @credentials={"type"=>"git_source", "host"=>"dev.azure.com", "username"=>"x-access-token", "password"=>***}, @auth_header={}, @max_retries=3> (NameError)

        user_id = get_user_id(token)
                              ^^^^^
	from ./update-script.rb:733:in `block in <main>'
	from ./update-script.rb:476:in `each'
	from ./update-script.rb:476:in `<main>'
Submitting @babel/cli pull request for creation.
```

**Comment by mburumaxwell** [comment]
Released in 0.13.2 couple of days ago
https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/0.13.2
