### ISSUE TITLE
Dependabot started to fail with `reject': undefined method `blank?' for ">= 2.1.0, < 2.1.29":String (NoMethodError)

### ISSUE THREAD

**Issue by davesmits** [tinglesoftware/dependabot-azure-devops#529]
No update needed for MicroElements.Swashbuckle.FluentValidation 5.7.0
Checking if Microsoft.AspNetCore.Authentication.JwtBearer 7.0.3 needs updating
bin/update-script.rb:314:in `reject': undefined method `blank?' for ">= 2.1.0, < 2.1.29":String (NoMethodError)

    vulnerable_versions = vulnerable_versions.reject(&:blank?).reject(&:empty?)
                                             ^^^^^^^
	from bin/update-script.rb:314:in `block in security_advisories_for'
	from bin/update-script.rb:303:in `map'
	from bin/update-script.rb:303:in `security_advisories_for'
	from bin/update-script.rb:546:in `block in <main>'
	from bin/update-script.rb:533:in `each'
	from bin/update-script.rb:533:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1

**Comment by mburumaxwell** [comment]
Hi @davesmits 
Some more context is needed here. Did this just start failing or is it a new package/setup? If so, which versions worked and which are failing?

From what I can see, the particular line of code failing was introduced in 0.14.0 via #470 which is over a month ago.

**Comment by davesmits** [comment]
It started to break with when it first time started to use this image

Unable to find image 'ghcr.io/tinglesoftware/dependabot-updater:0.15' locally
0.15: Pulling from tinglesoftware/dependabot-updater

the builds with 
Unable to find image 'tingle/dependabot-azure-devops:0.14' locally
0.14: Pulling from tingle/dependabot-azure-devops
did work; so it seesm 0.15 broke it

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/3148438/221245120-818a64f2-f6df-44bd-8d81-4fc6f04abd09.png">

its failing for .Net and Typescript / NPM and failing on different packages:

- Microsoft.AspNetCore.Authentication.JwtBearer
- Checking if Newtonsoft.Json 13.0.2 needs updating
- Checking if @angular/core 15.1.2 needs updating

**Comment by mburumaxwell** [comment]
I may need to do a public repro for this. It may take me sometime unless you already have one.

If indeed changing to GHCR affected you, setting `dockerImageTag: 0.14`, `dockerImageRegistry: ''`, and `dockerImageRepository: tingle/dependabot-azure-devops` inputs should work.

**Comment by davesmits** [comment]
just ran it with those settings applied and that worked again
<img width="523" alt="image" src="https://user-images.githubusercontent.com/3148438/221251126-2f7996eb-08e7-4644-9aa5-d65a48b0ffe3.png">

and 

<img width="289" alt="image" src="https://user-images.githubusercontent.com/3148438/221251218-2476f428-32dc-42d5-af0b-c140e05a50e2.png">

I dont have a repro right away but can spent tomorrow building one

**Comment by bdovaz** [comment]
Same problem here...

![image](https://user-images.githubusercontent.com/950602/221496157-06b072f9-a767-4e8e-b79c-dc130d0077d5.png)

**Comment by alex289** [comment]
> Same problem here...
> 
> ![image](https://user-images.githubusercontent.com/950602/221496157-06b072f9-a767-4e8e-b79c-dc130d0077d5.png)

+1

**Comment by gitolicious** [comment]
+2
For me, the issue is with `axios` in npm. An isolated run with just that dependency did succeed, so there wasn't an easy setup for a public repro.

**Comment by Seersha16** [comment]
Similar issue

<img width="478" alt="image" src="https://user-images.githubusercontent.com/61177817/221518518-7bcb1f5c-4146-47a8-8e0f-f6ea03a9ed19.png">

**Comment by DevDavido** [comment]
Same issue as mentioned before. Not an expert on Ruby here, but it seems related to the PR #523 where the use of ActiveSupport was removed, introduced with version 0.15.0.

> ActiveSupport that comes with Rails adds the blank? method to String and many other classes. Since this method is not part of Ruby core, you need to have Rails or the ActiveSupport gem installed.

**Comment by davesmits** [comment]
I got bit caught in family appointments so didnt had time for a public repo yet. will try to do later today

**Comment by bdovaz** [comment]
@mburumaxwell what do you have to do to get the version with this fix? Are you going to release it soon? Are you going to wait?

**Comment by mburumaxwell** [comment]
Expect a new release within the hour or the next. I will post back when that happens

**Comment by mburumaxwell** [comment]
A new release is now available [here](https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/0.16.0).
Note that the update may take time to show up in your organization. If it hasn;t updated, opening the extensions page will trigger an update.

**Comment by gitolicious** [comment]
Works like a charm. A big thanks for the quick fix!

**Comment by bdovaz** [comment]
Thanks @mburumaxwell !
