### ISSUE TITLE
Fails with error: `block in post': Dependabot::Clients::Azure::InternalServerError (Dependabot::Clients::Azure::InternalServerError)

### ISSUE THREAD

**Issue by NenoLoje** [tinglesoftware/dependabot-azure-devops#573]
## Error Message

The extension fails with error

```
2023-03-20T21:25:43.7068310Z 🌍 --> POST https://dev.azure.com/nenoalm/E2E/_apis/git/repositories/e2e-aspnetcore6/pushes?api-version=5.0
2023-03-20T21:25:43.8247114Z 🌍 <-- 500 https://dev.azure.com/nenoalm/E2E/_apis/git/repositories/e2e-aspnetcore6/pushes?api-version=5.0
2023-03-20T21:25:43.8250572Z /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/common/lib/dependabot/clients/azure.rb:303:in `block in post': Dependabot::Clients::Azure::InternalServerError (Dependabot::Clients::Azure::InternalServerError)
2023-03-20T21:25:43.8251938Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/common/lib/dependabot/clients/azure.rb:357:in `retry_connection_failures'
2023-03-20T21:25:43.8253006Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/common/lib/dependabot/clients/azure.rb:287:in `post'
2023-03-20T21:25:43.8254348Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/common/lib/dependabot/clients/azure.rb:168:in `create_commit'
2023-03-20T21:25:43.8255417Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/common/lib/dependabot/pull_request_creator/azure.rb:68:in `create_commit'
2023-03-20T21:25:43.8256620Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/common/lib/dependabot/pull_request_creator/azure.rb:36:in `create'
2023-03-20T21:25:43.8257668Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/common/lib/dependabot/pull_request_creator.rb:106:in `create'
2023-03-20T21:25:43.8258703Z 	from bin/update-script.rb:789:in `block in <main>'
2023-03-20T21:25:43.8259167Z 	from bin/update-script.rb:533:in `each'
2023-03-20T21:25:43.8259620Z 	from bin/update-script.rb:533:in `<main>'
2023-03-20T21:25:44.0027788Z ##[error]The process '/usr/bin/docker' failed with exit code 1
```
## Other parameters

* Environment: Azure DevOps Services
* Permissions: using PAT with Code (full) and PR Threads (read/write) scopes

**Comment by NenoLoje** [comment]
Full logs: [Dependabot-logs.txt](https://github.com/tinglesoftware/dependabot-azure-devops/files/11023254/Dependabot-logs.txt)

**Comment by MartinWa** [comment]
I have the same issue.

**Comment by MartinWa** [comment]
Looking at the code: https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/clients/azure.rb it seems that the 500 is coming from the Azure DevOps API: https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pushes/create?view=azure-devops-rest-5.0&tabs=HTTP

It is hard to test this without the JSON body (content). I can not see any way to get this info either. However I believe that it should be an Azure DevOps API issue as a 500 is never expected. I will retry in a few days.

**Comment by MartinWa** [comment]
I take that back, the Azure DevOps API does use 500 internal server error for bad requests...
I found this issue: https://github.com/dependabot/dependabot-core/issues/4263 and I then tested removing the "
Commit author email validation" repository settings. This allowed the commit to be created. The rule blocked it earlier as it had "Authored" by dependabot[bot].

I have tried to fix this using
`extraEnvironmentVariables: 
 GIT_AUTHOR_EMAIL=dependabot@xxx.com;GIT_AUTHOR_NAME=dependabot;AZURE_HOSTNAME=dev.azure.com'`
but that does not seem to work

**Comment by NenoLoje** [comment]
That's it! 

Turning off the "Commit author email validation" option temporarily fixed the issue:

![grafik](https://user-images.githubusercontent.com/13981145/226819766-e879280a-7abd-49db-b7be-d30e8614a188.png)

What e-mail address is Dependabot using for its commits? Is it customizable?

**Comment by mburumaxwell** [comment]
To get the full details of the request/response, add env variable `EXCON_DEBUG=1`

**Comment by NenoLoje** [comment]
As there's a workaround now, I'm closing this issue

Some ideas for follow-up requests:
- Provide a way to customize the e-mail address Depandabot is using
- Improve the error messages (by printing the JSON response on HTTP 5xx errors)

**Comment by NenoLoje** [comment]
> To get the full details of the request/response, add env variable `EXCON_DEBUG=1`

Thanks, @mburumaxwell !

FYI: The following commit information is sent to Azure DevOps:

* name: `dependabot[bot]`
* email: `noreply@github.com`

**Comment by mburumaxwell** [comment]
@NenoLoje the git author can be customized via `GIT_AUTHOR_EMAIL` and `GIT_AUTHOR_NAME`, did these never work for you?
I much rather have commits done by `dependabot[bot] (noreply@github.com)` for easier identification then squash merge the PR so that the commit in the default tree will now show the owner of the PAT.

As regards HTTP 5xx errors, this repository handles errors from creation of PRs but does not handle from pushing of commits. That explains why you could not see the error. The PR creation process is what is responsible for creating and pushing commits to a new branch. This is where you would need to catch the error and handle it appropriately, in the main repo. Contributions are welcome.

**Comment by MartinWa** [comment]
> @NenoLoje the git author can be customized via `GIT_AUTHOR_EMAIL` and `GIT_AUTHOR_NAME`, did these never work for you?

As I mentioned I have: 
`extraEnvironmentVariables: GIT_AUTHOR_EMAIL=dependabot@_<company domain>_.com;GIT_AUTHOR_NAME=dependabot;AZURE_HOSTNAME=dev.azure.com'`
But that does not seem to work, could this be the real cause of this issue?

>I much rather have commits done by `dependabot[bot] (noreply@github.com)` for easier identification then squash merge the PR
Yes but we want a trigger to block any email not from our domain to keep users from forgetting to set the git author / email fields. So in your case it would be the same use case just a different email address

**Comment by NenoLoje** [comment]
Indeed, as @MartinWa states - the `extraEnvironmentVariables` does not work as expected

**Comment by NenoLoje** [comment]
> I much rather have commits done by `dependabot[bot] (noreply@github.com)` for easier identification then squash merge the PR so that the commit in the default tree will now show the owner of the PAT.

Indeed, I would recommend **not** to use PATs (after all, there are "personal", as their name suggests). Instead, I use the access token from the build agent, which works great.

By doing this, the branches and PRs are showing as pushed by `<ProjectName> Build Service (<OrgName>)`.
