### ISSUE TITLE
Installing extension on Azure DevOps Server fails with error message

### ISSUE THREAD

**Issue by timmkrause** [tinglesoftware/dependabot-azure-devops#69]
We tried to install the extension on 2019 and 2020, both failed with the same message.

Error message:

`Task definition input 'useConfigFile' and Task definition input 'versioningStrategy' must belong to same group as they are dependent inputs for Task with ID 'd98b873d-cf18-41eb-8ff5-234f14697896'`

Stack trace:

    Microsoft.TeamFoundation.DistributedTask.WebApi.TaskDefinitionInvalidException: Task definition input 'useConfigFile' and Task definition input 'versioningStrategy' must belong to same group as they are dependent inputs for Task with ID 'd98b873d-cf18-41eb-8ff5-234f14697896'.
    at Microsoft.TeamFoundation.DistributedTask.Core.Server.TaskDefinitionValidator.CheckTaskDefinition(TaskDefinition taskDefinition, Action`1 taskInputDefinitionValidator)
    at Microsoft.TeamFoundation.DistributedTask.Core.Server.Plugins.TaskDefinitionExtensionPublishHandler.UpdateExtension(IVssRequestContext requestContext, PublishedExtension extension, PackageDetails packageDetails, Stream packageStream, String version, Guid validationId)
    at Microsoft.VisualStudio.Services.Gallery.Server.ExtensionVersionValidationService.InternalExecuteVersionValidation(IVssRequestContext requestContext, PublishedExtension extension, Stream packageStream, Guid validationId, Boolean& updateExtension, String& resultMessage)
    at Microsoft.VisualStudio.Services.Gallery.Server.ExtensionVersionValidationService.ProcessExtension(IVssRequestContext requestContext, PublishedExtension extension, Stream packageStream, Guid validationId, Guid vsid, String& resultMessage)

**Comment by timmkrause** [comment]
So we'll have to wait for the next release and then give it another shot, right?

**Comment by mburumaxwell** [comment]
@timmkrause yes, the next release should be ready tomorrow or the day after.

**Comment by mburumaxwell** [comment]
@timmkrause new release available.
However, I am not sure whether this will work with the Azure DevOps server. It appears [dependabot](https://github.com/dependabot/dependabot-core) is very specific on the URL/hostname format. See [this comment](https://github.com/tinglesoftware/dependabot-azure-devops/issues/27#issuecomment-768054722). But you can try and report back.
