### ISSUE TITLE
Unable to process gzipped data

### ISSUE THREAD

**Issue by arahja** [tinglesoftware/dependabot-azure-devops#712]
I setup a pipeline to run dependabot and part of the way through it runs into a gzipped payload of data and fails.

```
2023-07-17T22:02:00.6493715Z excon.response
2023-07-17T22:02:00.6497215Z   :body              => "\x1f\x8b\x08\x00\x8a\xe6\xb6d\x02\xff\xcd\x95M\x8f\x9b0\x10\x86\xff\n\xe2\x1cb>b\x02\x9c\xb6\xed\xb6R\x0f\xfdP\x95\\z\x89\x0c\x0c\xc5\xad\xf9\xa8\xc7!\xdd]\xf1\xdf;&I\xd5(\xea*\xab^8!\x8f\x87\xd7\xcf\xbc3\x86\'W\x96n\xe6\xe6<\x8c\xd28\x10^\x11\x87\xa1\xb7*\xf3\xd4\xcb9O\xbc\x14\x8a"O\xfc\xd4\xe7\tw\x17n+\x1a\xa0\xec\xb7\xbfD\xd3+X~\x84\xc3\xab\xbe\xa7\xf8^+\n\xd7\xc6\xf4\x981V\xc2\xb0\x14\x8f{\r\xcb\xa2k\xd8)\xf9\x1e\x86O=\xb2$^\xf3\xc8O\x13\x8fWq\xe2\xad\xc0\xe7\x9e\xc8y\xe1\xf1\xa2J\x8b4\x8cc^\x85l\'z\x89\xec\x9b4LC\xdf\xa14\x9d\x96\x80\xecF\xc8^w\xdf\xa10n\xf6t\xac\xed\x96#\xafj\xa3@\tXh\xd9\x1b\xd9\xb5\x14\xff d\xeb\x9c\xa4\x9d?X\x0fN\xd5i\xc7\xd4p\xdeB\xdaS\xc2@\xe9\x98\xce9\xfb\xf4"\x87\x8e\xc5\x9f\xe5\xd8\x8d\xf4h\xe8P:\xe1\x00J\xbd\xebt\x03%\x055\x0c\x12\'\xfc \xe0\x0b\xd7.r\xa9\xa4y\xa0\xc4^\xcb\xc1\xbe\xb2p\x95@\xb3\xedKZl\xe4dA\xe8\x87\x91\xe7G^\x10o\x02\x9e\xad\x92,\x88\x96\xc1j\xfd\xd5\x1d\xad)\x95\xd8+\xf3Z\x8b\xb6\xa8)WC\x85\xac\x06Q"kH\x07\xb4e\x91\x8f$\x13\xac\xa3\x80\xc7kK\xd1t\x06\xb6\x17\x06\\\x94|\xf7\x9c\x1d\xa7\x15\xdb\xd9q\xb8\x1a<\xc4\xfa(L\xbbw\xb4X^HeC\xf4\x0f\xb5+\xa1\x03\xe4\xdb\x9b[\xf4<\xd3N\xc9\xf6\x07\xda\xf1CP\x95}\xd6\xe4\xd2\\\xee\xc7xqANd\x03\x9a\xca\x92\xb174\x0c(+Y\x08;\xf6l\x03\xa2\xf9|\xcc\xbem\x10\xc7\xc9\xc9\x17\xd6\xfc\x9c\x9d\xe3\xd4\xe3\xbf\x04\xff\xaf\xd1$G\xe9\x8d48\xb3\xbe\xb03\xd6\xb8\x98\xee\xd4\xdc\xf0&&;;{\xa5\xbe\xc0\xcf=\xe0\xfc,\xbc`#Vi\xa0\x99\x1d\xe4\x11jr\x12k\x98\xa1\x87\x13\xd5h\xed\xc3{\x89"W\xf4+\xc9*\xa1\x10l\xe8}k\x7f\x84\x06Z\xfa\xfe\xc3)>\xfe\x06\xca\xec\xe2\x9fE\x08\x00\x00"
2023-07-17T22:02:00.6498871Z   :cookies           => [
2023-07-17T22:02:00.6499746Z     "VstsSession=%7B%22PersistentSessionId%22%3A%229f078805-235c-41cd-aeae-260ba824185d%22%2C%22PendingAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22CurrentAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22SignInState%22%3A%7B%7D%7D;SameSite=None; domain=.dev.azure.com; expires=Tue, 16-Jul-2024 22:02:00 GMT; path=/; secure; HttpOnly"
2023-07-17T22:02:00.6500237Z   ]
2023-07-17T22:02:00.6500335Z   :headers           => {
2023-07-17T22:02:00.6500552Z     "Access-Control-Expose-Headers" => "Request-Context"
2023-07-17T22:02:00.6500812Z     "ActivityId"                    => "15c4a556-20e9-4c9e-a1a1-14122cd7f93e"
2023-07-17T22:02:00.6501077Z     "Cache-Control"                 => "no-cache, no-store, must-revalidate"
2023-07-17T22:02:00.6501278Z     "Content-Encoding"              => "gzip"
2023-07-17T22:02:00.6501459Z     "Content-Length"                => "719"
2023-07-17T22:02:00.6501722Z     "Content-Type"                  => "application/json; charset=utf-8; api-version=7.0"
2023-07-17T22:02:00.6501905Z     "Date"                          => "Mon, 17 Jul 2023 22:02:00 GMT"
2023-07-17T22:02:00.6502062Z     "Expires"                       => "-1"
2023-07-17T22:02:00.6502247Z     "P3P"                           => "CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT""
2023-07-17T22:02:00.6502512Z     "Pragma"                        => "no-cache"
2023-07-17T22:02:00.6502785Z     "Request-Context"               => "appId=cid-v1:f88d1338-e7ba-4d7b-83e0-e573c40a2f62"
2023-07-17T22:02:00.6503760Z     "Set-Cookie"                    => "VstsSession=%7B%22PersistentSessionId%22%3A%229f078805-235c-41cd-aeae-260ba824185d%22%2C%22PendingAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22CurrentAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22SignInState%22%3A%7B%7D%7D;SameSite=None; domain=.dev.azure.com; expires=Tue, 16-Jul-2024 22:02:00 GMT; path=/; secure; HttpOnly"
2023-07-17T22:02:00.6504397Z     "Strict-Transport-Security"     => "max-age=31536000; includeSubDomains"
2023-07-17T22:02:00.6507126Z     "Vary"                          => "Accept-Encoding"
2023-07-17T22:02:00.6507345Z     "X-Cache"                       => "CONFIG_NOCACHE"
2023-07-17T22:02:00.6507748Z     "X-Content-Type-Options"        => "nosniff"
2023-07-17T22:02:00.6507958Z     "X-FRAME-OPTIONS"               => "SAMEORIGIN"
2023-07-17T22:02:00.6508302Z     "X-MSEdge-Ref"                  => "Ref A: B336D606959943B0BC6B2C7065D647AA Ref B: DM2EDGE0717 Ref C: 2023-07-17T22:02:00Z"
2023-07-17T22:02:00.6508624Z     "X-TFS-ProcessId"               => "f46d1fdb-bff0-4523-b6d1-9ef30cea5681"
2023-07-17T22:02:00.6508889Z     "X-TFS-Session"                 => "15c4a556-20e9-4c9e-a1a1-14122cd7f93e"
2023-07-17T22:02:00.6509166Z     "X-VSS-E2EID"                   => "15c4a556-20e9-4c9e-a1a1-14122cd7f93e"
2023-07-17T22:02:00.6509435Z     "X-VSS-SenderDeploymentId"      => "371dc233-5e58-9481-dadc-e75ac4f20939"
2023-07-17T22:02:00.6509798Z     "X-VSS-UserData"                => "cbbcbb27-41e6-455f-a5a5-656be8fb70b7:8afe9b99-c219-412c-9010-ef65f822bb0c"
2023-07-17T22:02:00.6509993Z   }
2023-07-17T22:02:00.6510101Z   :host              => "dev.azure.com"
2023-07-17T22:02:00.6510253Z   :local_address     => "172.17.0.2"
2023-07-17T22:02:00.6510380Z   :local_port        => 41044
2023-07-17T22:02:00.6510503Z   :method            => :get
2023-07-17T22:02:00.6510643Z   :omit_default_port => true
2023-07-17T22:02:00.6510805Z   :path              => "/ExampleDevOps/Example/_apis/git/repositories/Example.NewApp"
2023-07-17T22:02:00.6510969Z   :port              => 443
2023-07-17T22:02:00.6511078Z   :query             => nil
2023-07-17T22:02:00.6511191Z   :reason_phrase     => "OK"
2023-07-17T22:02:00.6511330Z   :remote_ip         => "13.107.42.20"
2023-07-17T22:02:00.6511451Z   :scheme            => "https"
2023-07-17T22:02:00.6511579Z   :status            => 200
2023-07-17T22:02:00.6511702Z   :status_line       => "HTTP/1.1 200 OK\r\n"
2023-07-17T22:02:00.6512197Z /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-8b4e7c7c59ff/common/lib/dependabot/clients/azure.rb:192:in `to_json': source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
2023-07-17T22:02:00.6512774Z    from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-8b4e7c7c59ff/common/lib/dependabot/clients/azure.rb:192:in `create_pull_request'
2023-07-17T22:02:00.6513318Z    from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-8b4e7c7c59ff/common/lib/dependabot/pull_request_creator/azure.rb:78:in `create_pull_request'
2023-07-17T22:02:00.6513827Z    from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-8b4e7c7c59ff/common/lib/dependabot/pull_request_creator/azure.rb:38:in `create'
2023-07-17T22:02:00.6514344Z    from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-8b4e7c7c59ff/common/lib/dependabot/pull_request_creator.rb:107:in `create'
2023-07-17T22:02:00.6514663Z    from bin/update-script.rb:844:in `block in <main>'
2023-07-17T22:02:00.6514883Z    from bin/update-script.rb:563:in `each'
2023-07-17T22:02:00.6515114Z    from bin/update-script.rb:563:in `<main>'
2023-07-17T22:02:00.8827159Z ##[debug]Exit code 1 received from tool '/usr/bin/docker'
2023-07-17T22:02:00.8834585Z ##[debug]STDIO streams have closed for tool '/usr/bin/docker'
2023-07-17T22:02:00.8888197Z ##[debug]task result: Failed
2023-07-17T22:02:00.8923308Z ##[error]The process '/usr/bin/docker' failed with exit code 1
2023-07-17T22:02:00.8932382Z ##[debug]Processed: ##vso[task.issue type=error;]The process '/usr/bin/docker' failed with exit code 1
2023-07-17T22:02:00.8942549Z ##[debug]Processed: ##vso[task.complete result=Failed;]The process '/usr/bin/docker' failed with exit code 1
2023-07-17T22:02:00.8977384Z ##[section]Finishing: dependabot
```
This is happening during a http GET operation. I am able to successfully decompress the gzipped body. Is there any way to tell the software to automatically decompress the body so that it can read the json that it contains?

**Comment by mburumaxwell** [comment]
Please provide a public repro for this

**Comment by mburumaxwell** [comment]
Reopen with repro
