### ISSUE TITLE
PR's description characters limit won't work

### ISSUE THREAD

**Issue by wooch82** [tinglesoftware/dependabot-azure-devops#723]
I have an error during PR creation with the latest version:
```Starting: dependabot
==============================================================================
Task         : Dependabot
Description  : Automatically update dependencies and vulnerabilities in your code
Version      : 1.20.526
Author       : Tingle Software
Help         : For help please visit https://github.com/tinglesoftware/dependabot-azure-devops
==============================================================================
```
```
Updating @rive-app/canvas from 1.2.1 to 2.0.0
Submitting @rive-app/canvas pull request for creation.
============
Failed! PR already exists or an error has occurred.
bin/update-script.rb:857:in `block in <main>': Pull Request creation failed with status 400. Message: Invalid argument value.\r (StandardError)
Parameter name: A description for a pull request must not be longer than 4000 characters.
	from bin/update-script.rb:563:in `each'
	from bin/update-script.rb:563:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1
```

**Comment by hbendev** [comment]
By the way, adding the ability to use the commit's description optionally, instead of this long summary would solve this and future cases of this issue. Related ticket: #579 

![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/22564005/981f7e36-91fd-4d84-baab-fe33f19b6350)

**Comment by mburumaxwell** [comment]
This is definitely a regression from https://github.com/dependabot/dependabot-core/pull/7487

Hopefully, there is a fix soon

**Comment by xwing3** [comment]
having the same issue as described above

**Comment by mburumaxwell** [comment]
This is fixed in #724.
Release notes: https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/1.20.1

@wooch82 , please close if it works for you.

@hbendev 
As mentioned in #579, the change proposed is not only major but requires a lot of time. It is most likely easier for Microsoft to increase the limit, but you can also have a go at it.

**Comment by wooch82** [comment]
Now it works, thank you.
But you just cut the descriptions out, maybe it's better at least give a link to release's notes.

**Comment by mburumaxwell** [comment]
Good to know.
Private feeds with repositories in Azure DevOps should also work unless they are not tagged.
