### ISSUE TITLE
Running Container Locally Getting (JSON::ParserError) during PR Creation Process

### ISSUE THREAD

**Issue by passionateprogrammersguild** [tinglesoftware/dependabot-azure-devops#73]
I have an azure devops repo and I am running the container locally based on the README for this project (nice job on the documentation).

I am getting the following output followed by the below error.  It looks like during the PR creation process nothing is returned ie empty string and as such I receive the Json Parse error.  I can provide more context if necessary but effectively I am running the command:

docker run --rm -t \
           -e AZURE_ACCESS_TOKEN={PAT}
           -e AZURE_ORGANIZATION={company_name} \
           -e AZURE_PROJECT={Project Name} \
           -e AZURE_REPOSITORY={project_name} \
           -e DEPENDABOT_PACKAGE_MANAGER=npm_and_yarn \
           -e DEPENDABOT_DIRECTORY={directory_name} \
           -e DEPENDABOT_TARGET_BRANCH=master \
           -e DEPENDABOT_VERSIONING_STRATEGY=widen \
           -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=10 \
           tingle/dependabot-azure-devops:0.2.0

OUTPUT / ERROR
===========================================
Using 'widen_ranges' versioning strategy
Parsing dependencies information
Checking if @angular-devkit/architect 0.1000.6 needs updating
Requirements to unlock own
Updating @angular-devkit/architect from 0.1000.6 to 0.1102.6
Submitting @angular-devkit/architect pull request for creation. Traceback (most recent call last):
        5: from ./update-script.rb:188:in `<main>'
        4: from ./update-script.rb:188:in `each'
        3: from ./update-script.rb:265:in `block in <main>'
        2: from /usr/lib/ruby/2.6.0/json/common.rb:15:in `[]'
        1: from /usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at '' (JSON::ParserError)

**Comment by passionateprogrammersguild** [comment]
The issue happened to the the PAT within Azure not having the proper permissions.  The PAT needed Code full access
