### ISSUE TITLE
[terraform] fails checking private git tf modules from ADO

### ISSUE THREAD

**Issue by davidkarlsen** [tinglesoftware/dependabot-azure-devops#756]
```
Checking if des::azure::MYORG/project/_git/terraform-azurerm-des::refs/tags/0.0.2 0.0.2 needs updating
🌍 --> GET https://dev.azure.com/MYORG/project/_git/terraform-azurerm-des/info/refs?service=git-upload-pack
🌍 <-- 200 https://dev.azure.com/MYORG/project/_git/terraform-azurerm-des/info/refs?service=git-upload-pack
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-terraform-0.225.0/lib/dependabot/terraform/update_checker.rb:127:in `latest_version_for_git_dependency': undefined method `match' for nil:NilClass (NoMethodError)

          return unless latest_tag.match(version_rgx)
                                  ^^^^^^
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-terraform-0.225.0/lib/dependabot/terraform/update_checker.rb:17:in `latest_version'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.225.0/lib/dependabot/update_checkers/base.rb:239:in `numeric_version_up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.225.0/lib/dependabot/update_checkers/base.rb:197:in `version_up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.225.0/lib/dependabot/update_checkers/base.rb:34:in `up_to_date?'
	from bin/update-script.rb:600:in `block in <main>'
	from bin/update-script.rb:563:in `each'
	from bin/update-script.rb:563:in `<main>'
```

**Comment by mburumaxwell** [comment]
Could this be better raised at https://github.com/dependabot/dependabot-core?
If you are certain it is ADO related from this repo (despite logs showing otherwise), you need to offer a public repro.
