### ISSUE TITLE
[npm] Repository not found when using AzDO extension

### ISSUE THREAD

**Issue by hangy** [tinglesoftware/dependabot-azure-devops#776]
**Describe the bug**
Using the AzDO extension on-prem with a virtual `tfs` directory, the Git repository cannot be cloned. Even though the Docker parameter `-e AZURE_VIRTUAL_DIRECTORY=tfs` is set correctly, 

**To Reproduce**
1. Create a YAML based DevOps pipeline that runs dependabot
2. Create a `.github/dependabot.yml` file in the repository
3. Run the YAML pipeline
4. See that the pipeline fails because it tries to clone `https://tfs.in.example.org/ExampleProjectCollection/OurTeamProject/_git/My.Repository/` instead of `https://tfs.in.example.org/tfs/ExampleProjectCollection/OurTeamProject/_git/My.Repository/`.

**Expected behavior**
Dependabot should be able to clone the repository.

**Screenshots**
N/A

**Extension (please complete the following information):**
 - Host: Azure DevOps Server 2022.0.1 (AzureDevOpsServer_20230721.2)
 - Version 1.20.3.543

**Server (please complete the following information):**
 - Region N/A
 - Version N/A

**Additional context**
<details>
<summary>.azure-pipelines/dependabot.yml</summary>

```yaml
trigger:
  batch: "true"
  branches:
    include:
      - main

schedules:
  - cron: "5 4 * * 0"
    displayName: Weekly check
    always: "true"
    branches:
      include:
        - main
    batch: "true"

pool: 'some-docker-pool'

steps:
  - task: dependabot@1
    inputs:
      useConfigFile: true
```
</details>

<details>
<summary>.github/dependabot.yml</summary>

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Some.Project"
    target-branch: main

  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: main
    ignore:
      - dependency-name: "Some.ThirdParty"
      - dependency-name: "Other.ThirdParty"
```
</details>

<details>
<summary>Build debug log</summary>

```
2023-09-06T12:43:48.8518240Z ##[debug]Evaluating condition for step: 'dependabot'
2023-09-06T12:43:48.8520765Z ##[debug]Evaluating: SucceededNode()
2023-09-06T12:43:48.8521029Z ##[debug]Evaluating SucceededNode:
2023-09-06T12:43:48.8521757Z ##[debug]=> True
2023-09-06T12:43:48.8522184Z ##[debug]Result: True
2023-09-06T12:43:48.8522507Z ##[section]dependabot wird gestartet.
2023-09-06T12:43:48.8532214Z ==============================================================================
2023-09-06T12:43:48.8532446Z Task         : Dependabot
2023-09-06T12:43:48.8532564Z Description  : Automatically update dependencies and vulnerabilities in your code
2023-09-06T12:43:48.8532690Z Version      : 1.20.543
2023-09-06T12:43:48.8532750Z Author       : Tingle Software
2023-09-06T12:43:48.8532816Z Help         : For help please visit https://github.com/tinglesoftware/dependabot-azure-devops
2023-09-06T12:43:48.8532925Z ==============================================================================
2023-09-06T12:43:48.9615764Z ##[debug]Using node path: /azdo/agent/externals/node16/bin/node
2023-09-06T12:43:49.0917011Z ##[debug]agent.TempDirectory=/azdo/agent/_work/_temp
2023-09-06T12:43:49.0923652Z ##[debug]loading inputs and endpoints
2023-09-06T12:43:49.0928592Z ##[debug]loading INPUT_USECONFIGFILE
2023-09-06T12:43:49.0938178Z ##[debug]loading INPUT_FAILONEXCEPTION
2023-09-06T12:43:49.0939245Z ##[debug]loading INPUT_SKIPPULLREQUESTS
2023-09-06T12:43:49.0940847Z ##[debug]loading INPUT_ABANDONUNWANTEDPULLREQUESTS
2023-09-06T12:43:49.0941882Z ##[debug]loading INPUT_SETAUTOCOMPLETE
2023-09-06T12:43:49.0945012Z ##[debug]loading INPUT_MERGESTRATEGY
2023-09-06T12:43:49.0946965Z ##[debug]loading INPUT_AUTOAPPROVE
2023-09-06T12:43:49.0949140Z ##[debug]loading INPUT_FORWARDHOSTSSHSOCKET
2023-09-06T12:43:49.0950284Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2023-09-06T12:43:49.0952788Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2023-09-06T12:43:49.0955992Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2023-09-06T12:43:49.0962261Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2023-09-06T12:43:49.0965205Z ##[debug]loaded 12
2023-09-06T12:43:49.0969002Z ##[debug]Agent.ProxyUrl=undefined
2023-09-06T12:43:49.0969867Z ##[debug]Agent.CAInfo=undefined
2023-09-06T12:43:49.0971295Z ##[debug]Agent.ClientCert=undefined
2023-09-06T12:43:49.0973085Z ##[debug]Agent.SkipCertValidation=undefined
2023-09-06T12:43:49.1505083Z ##[debug]useConfigFile=true
2023-09-06T12:43:49.1505499Z ##[debug]Checking for docker install ...
2023-09-06T12:43:49.1505831Z ##[debug]which 'docker'
2023-09-06T12:43:49.1521573Z ##[debug]found: '/usr/bin/docker'
2023-09-06T12:43:49.1522150Z ##[debug]System.TeamFoundationCollectionUri=https://tfs.in.example.org/tfs/ExampleProjectCollection/
2023-09-06T12:43:49.1724701Z ##[debug]System.TeamProject=OurTeamProject
2023-09-06T12:43:49.1725264Z ##[debug]targetRepositoryName=undefined
2023-09-06T12:43:49.1725642Z ##[debug]No custom repository provided. The Pipeline Repository Name shall be used.
2023-09-06T12:43:49.1726030Z ##[debug]Build.Repository.Name=My.Repository
2023-09-06T12:43:49.1726403Z ##[debug]gitHubAccessToken=undefined
2023-09-06T12:43:49.1726744Z ##[debug]gitHubConnection=undefined
2023-09-06T12:43:49.1727076Z ##[debug]azureDevOpsUser=undefined
2023-09-06T12:43:49.1727419Z ##[debug]azureDevOpsAccessToken=undefined
2023-09-06T12:43:49.1727757Z ##[debug]azureDevOpsServiceConnection=undefined
2023-09-06T12:43:49.1728138Z ##[debug]No custom token provided. The SystemVssConnection's AccessToken shall be used.
2023-09-06T12:43:49.1730395Z ##[debug]SystemVssConnection auth param AccessToken = ***
2023-09-06T12:43:49.1730842Z ##[debug]setAutoComplete=false
2023-09-06T12:43:49.1731191Z ##[debug]mergeStrategy=squash
2023-09-06T12:43:49.1731538Z ##[debug]autoCompleteIgnoreConfigIds=undefined
2023-09-06T12:43:49.1731862Z ##[debug]autoApprove=false
2023-09-06T12:43:49.1732291Z ##[debug]autoApproveUserToken=undefined
2023-09-06T12:43:49.1732625Z ##[debug]failOnException=true
2023-09-06T12:43:49.1732964Z ##[debug]excludeRequirementsToUnlock=undefined
2023-09-06T12:43:49.1733692Z ##[debug]updaterOptions=undefined
2023-09-06T12:43:49.1734034Z ##[debug]targetUpdateIds=undefined
2023-09-06T12:43:49.1734371Z ##[debug]securityAdvisoriesFile=undefined
2023-09-06T12:43:49.1734714Z ##[debug]skipPullRequests=false
2023-09-06T12:43:49.1735069Z ##[debug]abandonUnwantedPullRequests=false
2023-09-06T12:43:49.1735419Z ##[debug]extraEnvironmentVariables=undefined
2023-09-06T12:43:49.1735770Z ##[debug]forwardHostSshSocket=false
2023-09-06T12:43:49.1736109Z ##[debug]dockerImageRegistry=undefined
2023-09-06T12:43:49.1736441Z ##[debug]dockerImageTag=undefined
2023-09-06T12:43:49.1736831Z ##[debug]Getting dockerImageTag from task.json file. If you want to override, specify the dockerImageTag input
2023-09-06T12:43:49.1737249Z ##[debug]Build.SourcesDirectory=/azdo/agent/_work/1/s
2023-09-06T12:43:49.1737633Z ##[debug]No configuration file cloned at /azdo/agent/_work/1/s/.github/dependabot.yaml
2023-09-06T12:43:49.1738040Z ##[debug]Found configuration file cloned at /azdo/agent/_work/1/s/.github/dependabot.yml
2023-09-06T12:43:49.1739194Z ##[debug]Configuration file contents read.
2023-09-06T12:43:49.1780029Z ##[debug]Parsed YAML content from configuration file contents.
2023-09-06T12:43:49.1788198Z ##[debug]which 'docker'
2023-09-06T12:43:49.1792881Z ##[debug]found: '/usr/bin/docker'
2023-09-06T12:43:49.1793204Z ##[debug]which '/usr/bin/docker'
2023-09-06T12:43:49.1793530Z ##[debug]found: '/usr/bin/docker'
2023-09-06T12:43:49.1794690Z ##[debug]/usr/bin/docker arg: ["run"]
2023-09-06T12:43:49.1795093Z ##[debug]/usr/bin/docker arg: ["--rm"]
2023-09-06T12:43:49.1795438Z ##[debug]/usr/bin/docker arg: ["-i"]
2023-09-06T12:43:49.1795795Z ##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_PACKAGE_MANAGER=npm"]
2023-09-06T12:43:49.1796197Z ##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5"]
2023-09-06T12:43:49.1796595Z ##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_DIRECTORY=/My.Repository"]
2023-09-06T12:43:49.1796967Z ##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_TARGET_BRANCH=main"]
2023-09-06T12:43:49.1797352Z ##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_FAIL_ON_EXCEPTION=true"]
2023-09-06T12:43:49.1797735Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_ORGANIZATION=ExampleProjectCollection"]
2023-09-06T12:43:49.1798115Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_PROJECT=OurTeamProject"]
2023-09-06T12:43:49.1798528Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_REPOSITORY=My.Repository"]
2023-09-06T12:43:49.1800434Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_ACCESS_TOKEN=***"]
2023-09-06T12:43:49.1801229Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_MERGE_STRATEGY=squash"]
2023-09-06T12:43:49.1801632Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_HOSTNAME=tfs.in.example.org"]
2023-09-06T12:43:49.1802031Z ##[debug]/usr/bin/docker arg: ["-e","AZURE_VIRTUAL_DIRECTORY=tfs"]
2023-09-06T12:43:49.1802477Z ##[debug]Running docker container -> 'ghcr.io/tinglesoftware/dependabot-updater-npm:1.20' ...
2023-09-06T12:43:49.1802913Z ##[debug]/usr/bin/docker arg: ghcr.io/tinglesoftware/dependabot-updater-npm:1.20
2023-09-06T12:43:49.1803289Z ##[debug]exec tool: /usr/bin/docker
2023-09-06T12:43:49.1803606Z ##[debug]arguments:
2023-09-06T12:43:49.1803909Z ##[debug]   run
2023-09-06T12:43:49.1804191Z ##[debug]   --rm
2023-09-06T12:43:49.1804485Z ##[debug]   -i
2023-09-06T12:43:49.1804859Z ##[debug]   -e
2023-09-06T12:43:49.1805275Z ##[debug]   DEPENDABOT_PACKAGE_MANAGER=npm
2023-09-06T12:43:49.1805714Z ##[debug]   -e
2023-09-06T12:43:49.1806163Z ##[debug]   DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5
2023-09-06T12:43:49.1806673Z ##[debug]   -e
2023-09-06T12:43:49.1807102Z ##[debug]   DEPENDABOT_DIRECTORY=/My.Repository
2023-09-06T12:43:49.1807437Z ##[debug]   -e
2023-09-06T12:43:49.1807752Z ##[debug]   DEPENDABOT_TARGET_BRANCH=main
2023-09-06T12:43:49.1808067Z ##[debug]   -e
2023-09-06T12:43:49.1808371Z ##[debug]   DEPENDABOT_FAIL_ON_EXCEPTION=true
2023-09-06T12:43:49.1808690Z ##[debug]   -e
2023-09-06T12:43:49.1809014Z ##[debug]   AZURE_ORGANIZATION=ExampleProjectCollection
2023-09-06T12:43:49.1809537Z ##[debug]   -e
2023-09-06T12:43:49.1809866Z ##[debug]   AZURE_PROJECT=OurTeamProject
2023-09-06T12:43:49.1810177Z ##[debug]   -e
2023-09-06T12:43:49.1810497Z ##[debug]   AZURE_REPOSITORY=My.Repository
2023-09-06T12:43:49.1810871Z ##[debug]   -e
2023-09-06T12:43:49.1812298Z ##[debug]   AZURE_ACCESS_TOKEN=***
2023-09-06T12:43:49.1812652Z ##[debug]   -e
2023-09-06T12:43:49.1812958Z ##[debug]   AZURE_MERGE_STRATEGY=squash
2023-09-06T12:43:49.1813341Z ##[debug]   -e
2023-09-06T12:43:49.1813664Z ##[debug]   AZURE_HOSTNAME=tfs.in.example.org
2023-09-06T12:43:49.1813988Z ##[debug]   -e
2023-09-06T12:43:49.1814301Z ##[debug]   AZURE_VIRTUAL_DIRECTORY=tfs
2023-09-06T12:43:49.1814668Z ##[debug]   ghcr.io/tinglesoftware/dependabot-updater-npm:1.20
2023-09-06T12:43:49.1817873Z [command]/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=npm -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5 -e DEPENDABOT_DIRECTORY=/My.Repository -e DEPENDABOT_TARGET_BRANCH=main -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e AZURE_ORGANIZATION=ExampleProjectCollection -e AZURE_PROJECT=OurTeamProject -e AZURE_REPOSITORY=My.Repository -e AZURE_ACCESS_TOKEN=*** -e AZURE_MERGE_STRATEGY=squash -e AZURE_HOSTNAME=tfs.in.example.org -e AZURE_VIRTUAL_DIRECTORY=tfs ghcr.io/tinglesoftware/dependabot-updater-npm:1.20
2023-09-06T12:43:49.2268352Z Unable to find image 'ghcr.io/tinglesoftware/dependabot-updater-npm:1.20' locally
2023-09-06T12:43:49.7567158Z 1.20: Pulling from tinglesoftware/dependabot-updater-npm
2023-09-06T12:43:49.7567691Z 7007490126ef: Already exists
2023-09-06T12:43:49.7697469Z fc9716c20f27: Already exists
2023-09-06T12:43:49.7902536Z f4e264570f96: Already exists
2023-09-06T12:43:49.8104236Z 4f4fb700ef54: Already exists
2023-09-06T12:43:49.8324675Z 7c15a8b79874: Already exists
2023-09-06T12:43:49.8527343Z 413d0250437e: Already exists
2023-09-06T12:43:49.8729023Z 89d5dcc86788: Already exists
2023-09-06T12:43:49.8935171Z 5b5bcc353232: Already exists
2023-09-06T12:43:49.9135998Z 3f0cd08293fa: Already exists
2023-09-06T12:43:49.9340206Z 967a809c0787: Already exists
2023-09-06T12:43:49.9542840Z ab86243985c9: Already exists
2023-09-06T12:43:49.9745140Z 678befbdd70b: Already exists
2023-09-06T12:43:49.9952726Z 580228e96812: Already exists
2023-09-06T12:43:50.0153384Z a5fa24eb05ba: Already exists
2023-09-06T12:43:50.0354519Z dbe67293b02f: Already exists
2023-09-06T12:43:50.0562441Z 24f1172a41c3: Already exists
2023-09-06T12:43:50.0769985Z 8ef48141a91d: Already exists
2023-09-06T12:43:50.0973957Z a3a2ed5b8c80: Already exists
2023-09-06T12:43:50.1181319Z dba12b8f8c5d: Already exists
2023-09-06T12:43:50.1385814Z e6928fe1f059: Already exists
2023-09-06T12:43:50.1595388Z 73caeae900e4: Already exists
2023-09-06T12:43:50.1799775Z 42852d6ec931: Already exists
2023-09-06T12:43:50.2008764Z 5dc862751526: Already exists
2023-09-06T12:43:50.2216133Z 0e1be8b320eb: Already exists
2023-09-06T12:43:50.2421239Z a403d7da4c0a: Already exists
2023-09-06T12:43:50.2626130Z 6377b2d3d744: Already exists
2023-09-06T12:43:50.2832310Z c739b067771f: Already exists
2023-09-06T12:43:50.3036406Z 4f4fb700ef54: Already exists
2023-09-06T12:43:50.3249322Z 2fd135d54fa1: Already exists
2023-09-06T12:43:50.3452731Z 492b40917afd: Already exists
2023-09-06T12:43:50.3661352Z 43e90a1c2482: Already exists
2023-09-06T12:43:50.3871031Z 3eac3a4bc583: Already exists
2023-09-06T12:43:50.4073995Z 16cdb88d922e: Pulling fs layer
2023-09-06T12:43:50.4077036Z 5ce68621c22c: Pulling fs layer
2023-09-06T12:43:50.4077321Z 41274a855045: Pulling fs layer
2023-09-06T12:43:50.4077556Z 8ffe568aaf69: Pulling fs layer
2023-09-06T12:43:50.4077819Z 52d7aa502d2f: Pulling fs layer
2023-09-06T12:43:50.4078027Z 33823b274f7a: Pulling fs layer
2023-09-06T12:43:50.4078233Z 8ffe568aaf69: Waiting
2023-09-06T12:43:50.4078433Z d6fc671631db: Pulling fs layer
2023-09-06T12:43:50.4078659Z 21b60b1b6a10: Pulling fs layer
2023-09-06T12:43:50.4078867Z a35889ea8b67: Pulling fs layer
2023-09-06T12:43:50.4079059Z 33823b274f7a: Waiting
2023-09-06T12:43:50.4079265Z d6fc671631db: Waiting
2023-09-06T12:43:50.4079788Z 52d7aa502d2f: Waiting
2023-09-06T12:43:50.4080010Z a103dc10c935: Pulling fs layer
2023-09-06T12:43:50.4080203Z a35889ea8b67: Waiting
2023-09-06T12:43:50.4080402Z 4f4fb700ef54: Pulling fs layer
2023-09-06T12:43:50.4080624Z 6387fc31eaab: Pulling fs layer
2023-09-06T12:43:50.4080817Z 4f4fb700ef54: Waiting
2023-09-06T12:43:50.4081178Z 6387fc31eaab: Waiting
2023-09-06T12:43:50.4081385Z a103dc10c935: Waiting
2023-09-06T12:43:50.4081606Z fdedee70b1d5: Pulling fs layer
2023-09-06T12:43:50.4081837Z 0ad56456e5f1: Pulling fs layer
2023-09-06T12:43:50.4082027Z fdedee70b1d5: Waiting
2023-09-06T12:43:50.4082232Z 0ad56456e5f1: Waiting
2023-09-06T12:43:50.4082440Z d9485f88480d: Pulling fs layer
2023-09-06T12:43:50.4082632Z d9485f88480d: Waiting
2023-09-06T12:43:50.7637138Z 5ce68621c22c: Verifying Checksum
2023-09-06T12:43:50.7637438Z 5ce68621c22c: Download complete
2023-09-06T12:43:50.9099949Z 41274a855045: Verifying Checksum
2023-09-06T12:43:50.9100317Z 41274a855045: Download complete
2023-09-06T12:43:51.1653013Z 8ffe568aaf69: Verifying Checksum
2023-09-06T12:43:51.1653395Z 8ffe568aaf69: Download complete
2023-09-06T12:43:51.2881857Z 52d7aa502d2f: Verifying Checksum
2023-09-06T12:43:51.2882140Z 52d7aa502d2f: Download complete
2023-09-06T12:43:51.6307223Z d6fc671631db: Verifying Checksum
2023-09-06T12:43:51.6307673Z d6fc671631db: Download complete
2023-09-06T12:43:51.7000614Z 16cdb88d922e: Verifying Checksum
2023-09-06T12:43:51.7001144Z 16cdb88d922e: Download complete
2023-09-06T12:43:52.1712892Z a35889ea8b67: Verifying Checksum
2023-09-06T12:43:52.1713217Z a35889ea8b67: Download complete
2023-09-06T12:43:52.2354936Z 21b60b1b6a10: Verifying Checksum
2023-09-06T12:43:52.2355270Z 21b60b1b6a10: Download complete
2023-09-06T12:43:52.4731145Z 4f4fb700ef54: Verifying Checksum
2023-09-06T12:43:52.4731496Z 4f4fb700ef54: Download complete
2023-09-06T12:43:52.5735850Z 33823b274f7a: Verifying Checksum
2023-09-06T12:43:52.5736235Z 33823b274f7a: Download complete
2023-09-06T12:43:52.5782583Z a103dc10c935: Verifying Checksum
2023-09-06T12:43:52.5783064Z a103dc10c935: Download complete
2023-09-06T12:43:52.8175976Z 6387fc31eaab: Verifying Checksum
2023-09-06T12:43:52.8176335Z 6387fc31eaab: Download complete
2023-09-06T12:43:52.9648114Z 0ad56456e5f1: Download complete
2023-09-06T12:43:53.1540557Z fdedee70b1d5: Verifying Checksum
2023-09-06T12:43:53.1540919Z fdedee70b1d5: Download complete
2023-09-06T12:43:53.1771825Z d9485f88480d: Verifying Checksum
2023-09-06T12:43:53.1773003Z d9485f88480d: Download complete
2023-09-06T12:43:55.2589066Z 16cdb88d922e: Pull complete
2023-09-06T12:43:55.5362624Z 5ce68621c22c: Pull complete
2023-09-06T12:43:56.2537096Z 41274a855045: Pull complete
2023-09-06T12:43:56.5486976Z 8ffe568aaf69: Pull complete
2023-09-06T12:43:56.9021557Z 52d7aa502d2f: Pull complete
2023-09-06T12:44:03.8238125Z 33823b274f7a: Pull complete
2023-09-06T12:44:04.0888096Z d6fc671631db: Pull complete
2023-09-06T12:44:05.0222363Z 21b60b1b6a10: Pull complete
2023-09-06T12:44:05.5171142Z a35889ea8b67: Pull complete
2023-09-06T12:44:05.9335202Z a103dc10c935: Pull complete
2023-09-06T12:44:06.2359527Z 4f4fb700ef54: Pull complete
2023-09-06T12:44:06.5162668Z 6387fc31eaab: Pull complete
2023-09-06T12:44:07.8385994Z fdedee70b1d5: Pull complete
2023-09-06T12:44:08.1262229Z 0ad56456e5f1: Pull complete
2023-09-06T12:44:08.4246878Z d9485f88480d: Pull complete
2023-09-06T12:44:08.4545678Z Digest: sha256:b94cc2ab963a132dc3019bf91dca66ab9f7da52412dcf699a92c0686b93bcd55
2023-09-06T12:44:08.4746218Z Status: Downloaded newer image for ghcr.io/tinglesoftware/dependabot-updater-npm:1.20
2023-09-06T12:44:11.5735026Z Using 'https://tfs.in.example.org:443/tfs/' as API endpoint
2023-09-06T12:44:11.5736168Z Working in ExampleProjectCollection/OurTeamProject/_git/My.Repository, 'main' branch under '/My.Repository' directory
2023-09-06T12:44:11.5736585Z Looking for configuration file in the repository ...
2023-09-06T12:44:11.5739399Z 🌍 --> GET https://tfs.in.example.org/tfs/ExampleProjectCollection/OurTeamProject/_apis/git/repositories/My.Repository/stats/branches?name=main
2023-09-06T12:44:11.6119869Z 🌍 <-- 200 https://tfs.in.example.org/tfs/ExampleProjectCollection/OurTeamProject/_apis/git/repositories/My.Repository/stats/branches?name=main
2023-09-06T12:44:11.6121113Z 🌍 --> GET https://tfs.in.example.org/tfs/ExampleProjectCollection/OurTeamProject/_apis/git/repositories/My.Repository/items?path=.github/dependabot.yml&versionDescriptor.versionType=commit&versionDescriptor.version=8a158b9c391f91d59ecd549a2b1eb41255a1021a
2023-09-06T12:44:11.6420076Z 🌍 <-- 200 https://tfs.in.example.org/tfs/ExampleProjectCollection/OurTeamProject/_apis/git/repositories/My.Repository/items?path=.github/dependabot.yml&versionDescriptor.versionType=commit&versionDescriptor.version=8a158b9c391f91d59ecd549a2b1eb41255a1021a
2023-09-06T12:44:11.6421069Z Using configuration file at '/.github/dependabot.yml' 😎
2023-09-06T12:44:11.6444700Z Cloning repository into /home/dependabot/dependabot-updater/tmp/ExampleProjectCollection/OurTeamProject/_git/My.Repository
2023-09-06T12:44:11.7887532Z /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.227.0/lib/dependabot/file_fetchers/base.rb:102:in `rescue in clone_repo_contents': Dependabot::RepoNotFound (Dependabot::RepoNotFound)
2023-09-06T12:44:11.7888521Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.227.0/lib/dependabot/file_fetchers/base.rb:92:in `clone_repo_contents'
2023-09-06T12:44:11.7889638Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.227.0/lib/dependabot/npm_and_yarn/file_fetcher.rb:41:in `clone_repo_contents'
2023-09-06T12:44:11.7890044Z 	from bin/update-script.rb:524:in `<main>'
2023-09-06T12:44:11.7908319Z /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.227.0/lib/dependabot/shared_helpers.rb:352:in `run_shell_command': Cloning into '/home/dependabot/dependabot-updater/tmp/ExampleProjectCollection/OurTeamProject/_git/My.Repository'... (Dependabot::SharedHelpers::HelperSubprocessFailed)
2023-09-06T12:44:11.7909437Z fatal: repository 'https://tfs.in.example.org/ExampleProjectCollection/OurTeamProject/_git/My.Repository/' not found
2023-09-06T12:44:11.7910013Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.227.0/lib/dependabot/file_fetchers/base.rb:628:in `block in _clone_repo_contents'
2023-09-06T12:44:11.7910783Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.227.0/lib/dependabot/shared_helpers.rb:187:in `with_git_configured'
2023-09-06T12:44:11.7911364Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.227.0/lib/dependabot/file_fetchers/base.rb:609:in `_clone_repo_contents'
2023-09-06T12:44:11.7912148Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.227.0/lib/dependabot/file_fetchers/base.rb:94:in `clone_repo_contents'
2023-09-06T12:44:11.7914733Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.227.0/lib/dependabot/npm_and_yarn/file_fetcher.rb:41:in `clone_repo_contents'
2023-09-06T12:44:11.7915303Z 	from bin/update-script.rb:524:in `<main>'
2023-09-06T12:44:12.9769325Z ##[debug]Exit code 1 received from tool '/usr/bin/docker'
2023-09-06T12:44:12.9775625Z ##[debug]STDIO streams have closed for tool '/usr/bin/docker'
2023-09-06T12:44:12.9816896Z ##[debug]task result: Failed
2023-09-06T12:44:12.9860459Z ##[error]The process '/usr/bin/docker' failed with exit code 1
2023-09-06T12:44:12.9870411Z ##[debug]Processed: ##vso[task.issue type=error;]The process '/usr/bin/docker' failed with exit code 1
2023-09-06T12:44:12.9877651Z ##[debug]Processed: ##vso[task.complete result=Failed;]The process '/usr/bin/docker' failed with exit code 1
2023-09-06T12:44:12.9902831Z ##[section]dependabot wird fertiggstellt
```
</details>

I'm not sure if this is a regression in [dependabot-azure-devops](https://github.com/tinglesoftware/dependabot-azure-devops) (possibly #112/#115), or if it's related to a updated [upstream](https://github.com/dependabot/dependabot-core/) behaviour.

**Comment by hangy** [comment]
Note: `ghcr.io/tinglesoftware/dependabot-updater-nuget:1.20` and `ghcr.io/tinglesoftware/dependabot-updater-docker:1.20`, which don't seem to clone the repo, and just download some config files directly, work. Looks like the issue is distinct to the `ghcr.io/tinglesoftware/dependabot-updater-npm:1.20` image (or to what's run inside).

**Comment by mburumaxwell** [comment]
Cloning is a behavior required by dependabot based on the package ecosystem. Without it, the shared helpers (e.g npm updating the lockfile) may not work because they require local files. Docker and nuget support is purely based on regular expressions (no local tools) hence no need to clone.

In this particular case, it appears strange that the same setup for `source` works when retrieving the branches and the configuration file. Could the clone URL be different?

Since this is an OnPrem setup and I have no access, could you try and reproduce the problem with the [dry-run.rb script](https://github.com/dependabot/dependabot-core/blob/main/bin/dry-run.rb)?

**Comment by hangy** [comment]
> Since this is an OnPrem setup and I have no access, could you try and reproduce the problem with the [dry-run.rb script](https://github.com/dependabot/dependabot-core/blob/main/bin/dry-run.rb)?

I just tried that, but I'm having a few issues building the dev image with their script, right now.

**Comment by mburumaxwell** [comment]
I have no clue what id going on here, to be honest. How long has this been going on?
It could also be an issue from upstream but I have no clue where else to being.

**Comment by mburumaxwell** [comment]
Closing this as due to lack of enough information for reproduction/investigation.
