### ISSUE TITLE
Authenticate with private organization registry

### ISSUE THREAD

**Issue by ChrisDoddGit** [tinglesoftware/dependabot-azure-devops#828]
Hello,

I'm curious if dependabot supports authentication with a private hosted registry? I am able to authenticate with Azure artifacts if the url is replaced; however, I'm now try to authenticate with my company hosted Jfrog artifactory npm registry.

Thanks in advance as we have recently migrated our packages.

Dependabot version:
1.20.543

Config:

```yml
version: 2
registries:
  flow:
    type: npm-registry
    token: PAT:${{JFROG_PAT}}
    url: https://artifacts.developer.**my.org**/artifactory/api/npm/aba7-npm/
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 15
    target-branch: 'develop'
    milestone: 3499
    registries:
    - flow
```

When running this pipeline I get the error:

```txt
Checking if @research/d3-bar 0.2.0 needs updating
🌍 --> GET https://artifacts.developer**my.org**/artifactory/api/npm/aba7-npm/@research%2Fd3-bar
🌍 <-- 401 https://artifacts.developer.**my.org**/artifactory/api/npm/aba7-npm/@research%2Fd3-bar
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.232.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:316:in `check_npm_response': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): artifacts.developer.**my.org**/artifactory/api/npm/aba7-npm/ (Dependabot::PrivateSourceAuthenticationFailure)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.232.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:275:in `fetch_npm_details'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.232.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:269:in `npm_details'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.232.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:111:in `valid_npm_details?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.232.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:37:in `latest_version_from_registry'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.232.0/lib/dependabot/npm_and_yarn/update_checker.rb:302:in `latest_released_version'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.232.0/lib/dependabot/npm_and_yarn/update_checker.rb:310:in `latest_version_details'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.232.0/lib/dependabot/npm_and_yarn/update_checker.rb:40:in `latest_version'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.232.0/lib/dependabot/update_checkers/base.rb:240:in `numeric_version_up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.232.0/lib/dependabot/update_checkers/base.rb:198:in `version_up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.232.0/lib/dependabot/update_checkers/base.rb:35:in `up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.232.0/lib/dependabot/npm_and_yarn/update_checker.rb:28:in `up_to_date?'
	from bin/update_script.rb:602:in `block in <main>'
	from bin/update_script.rb:565:in `each'
	from bin/update_script.rb:565:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1
```

**Comment by ChrisDoddGit** [comment]
Alternatively (less ideal), support to ignore a scope would be an ok work around!

**Comment by mburumaxwell** [comment]
The configuration of private registries is the same irrespective of the host.
You can try making a request to the same URL using Postman/Insomnia with the credentials as you set them up to ascertain configuration.
Your .npmrc file also needs to be aligned.

I don't know how to ignore scopes on npm or dependabot so I can't help with that.
