### ISSUE TITLE
Issues when trying to update a package,

### ISSUE THREAD

**Issue by ryanbowden** [tinglesoftware/dependabot-azure-devops#840]
**Describe the bug**
For some reason when trying to update a package from a private source it is failing, Checked and updated the PAT token but still having same issue and does not suggest there is an issue with the pat token throws the following error:

```/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-4bcf888f8823/common/lib/dependabot/shared_helpers.rb:132:in `run_helper_subprocess': Unable to authenticate, need: Bearer authorization_uri=https://login.windows.net/{guid-removed-here}, Basic realm="[https://pkgsproduks1.pkgs.visualstudio.com/",](https://pkgsproduks1.pkgs.visualstudio.com/%22,) TFS-Federated (Dependabot::SharedHelpers::HelperSubprocessFailed)```

Full output
```
Checking if @tag/tag-components-react-v4 4.3.0 needs updating
🌍 --> GET https://pkgs.dev.azure.com/{URL-REMOVED}/@tag%2Ftag-components-react-v4
🌍 <-- 200 https://pkgs.dev.azure.com/{URL-REMOVED}/@tag%2Ftag-components-react-v4
🌍 --> GET https://pkgs.dev.azure.com/{URL-REMOVED}y/@tag%2Ftag-components-react-v4/4.15.0
🌍 <-- 404 https://pkgs.dev.azure.com/{URL-REMOVED}/@tag%2Ftag-components-react-v4/4.15.0
🌍 --> GET https://pkgs.dev.azure.com/{URL-REMOVED}/@tag/tag-components-react-v4/4.15.0
🌍 <-- 404 https://pkgs.dev.azure.com/{URL-REMOVED}/@tag/tag-components-react-v4/4.15.0
🌍 --> GET https://pkgs.dev.azure.com/{URL-REMOVED}@tag%2Ftag-components-react-v4/latest
🌍 <-- 404 https://pkgs.dev.azure.com/{URL-REMOVED}/@tag%2Ftag-components-react-v4/latest
Requirements to unlock own
Requirements update strategy bump_versions
Updating @tag/tag-components-react-v4 from 4.3.0 to 4.15.0
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-4bcf888f8823/common/lib/dependabot/shared_helpers.rb:132:in `run_helper_subprocess': Unable to authenticate, need: Bearer authorization_uri=https://login.windows.net/GUID-Removed}, Basic realm="[https://pkgsproduks1.pkgs.visualstudio.com/",](https://pkgsproduks1.pkgs.visualstudio.com/%22,) TFS-Federated (Dependabot::SharedHelpers::HelperSubprocessFailed)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-4bcf888f8823/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:163:in `run_npm_top_level_updater'

```

**Expected behavior**
A Pr to have been raised 

**Screenshots**
Can add screenshots but just as above

**Extension (please complete the following information):**
 - latest version plus this tag saw fixed for others"1.21.1-pullrequest0829-0052"

**Additional context**
Happy to share any more details needed

**Comment by ryanbowden** [comment]
Found the issue i needed to create a new PAt token not just extend the one i had
