### ISSUE TITLE
Error while submitting pull request

### ISSUE THREAD

**Issue by XmlmXmlmX** [tinglesoftware/dependabot-azure-devops#96]
What is missing? 

# Pipeline YAML:

```yml
trigger: none # Disable CI trigger

schedules:
- cron: '0 2 * * *' # daily at 2am UTC
  always: true # run even when there are no code changes
  branches:
    include:
      - master
  batch: true
  displayName: Daily

pool:
  vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)

steps:
- task: dependabot@1
  inputs:
    packageManager: 'nuget'
```

# Log:

```log
Updating Microsoft.ApplicationInsights from 2.12.1 to 2.17.0
Submitting Microsoft.ApplicationInsights pull request for creation. Error updating Microsoft.ApplicationInsights from 2.12.1 to 2.17.0 (continuing)
/home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/response/raise_error.rb:14:in `on_complete': GET https://api.github.com/repos/Microsoft/ApplicationInsights-dotnet/contents/: 403 - API rate limit exceeded for 13.74.71.245. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting (Octokit::TooManyRequests)
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.4.1/lib/faraday/middleware.rb:19:in `block in call'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.4.1/lib/faraday/response.rb:59:in `on_complete'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.4.1/lib/faraday/middleware.rb:18:in `call'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.4.1/lib/faraday/request/retry.rb:148:in `call'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.4.1/lib/faraday/rack_builder.rb:154:in `build_response'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.4.1/lib/faraday/connection.rb:492:in `run_request'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-1.4.1/lib/faraday/connection.rb:198:in `get'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/connection.rb:156:in `request'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/connection.rb:19:in `get'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/client/contents.rb:40:in `contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/clients/github_with_retries.rb:95:in `public_send'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/clients/github_with_retries.rb:95:in `block in method_missing'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/clients/github_with_retries.rb:115:in `retry_connection_failures'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/clients/github_with_retries.rb:92:in `method_missing'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/metadata_finders/base/changelog_finder.rb:259:in `fetch_github_file_list'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/metadata_finders/base/changelog_finder.rb:241:in `fetch_dependency_file_list'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/metadata_finders/base/changelog_finder.rb:236:in `dependency_file_list'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/metadata_finders/base/changelog_finder.rb:135:in `changelog_from_ref'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/metadata_finders/base/changelog_finder.rb:123:in `default_branch_changelog'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/metadata_finders/base/changelog_finder.rb:86:in `changelog'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/metadata_finders/base/changelog_finder.rb:34:in `changelog_url'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/metadata_finders/base.rb:40:in `changelog_url'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/pull_request_creator/message_builder.rb:327:in `changelog_url'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/pull_request_creator/message_builder.rb:292:in `metadata_links_for_dep'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/pull_request_creator/message_builder.rb:279:in `metadata_links'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/pull_request_creator/message_builder.rb:56:in `commit_message'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/pull_request_creator.rb:171:in `azure_creator'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/pull_request_creator.rb:104:in `create'
	from ./update-script.rb:374:in `block in <main>'
	from ./update-script.rb:222:in `each'
	from ./update-script.rb:222:in `<main>'
```

**Comment by mburumaxwell** [comment]
You are hitting rate-limiting on the GitHub API because your requests to GitHub are unauthenticated. You need to supply a `githubConnection` so that your requests are authenticated. dependabot makes requests to GitHub to get release notes and/or changelog. The requests tend to be quite a number.
