### ISSUE TITLE
Error while running dependabot

### ISSUE THREAD

**Issue by Exanis** [tinglesoftware/dependabot-azure-devops#97]
There seems to be an error when starting the configuration, but I can't find what...

### Pipeline YAML

```trigger: none # Disable CI trigger

pool:
  vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)

steps:
- task: dependabot@1
  inputs:
    packageManager: 'pip'
    directory: '/arena'
    failOnException: false
    setAutoComplete: true
    targetRepositoryName: 'api-arena'
- task: dependabot@1
  inputs:
    packageManager: 'npm'
    directory: '/'
    failOnException: false
    setAutoComplete: true
    targetRepositoryName: 'ui-forge'
```

### Result log

```[...]
5bc9af957871: Pull complete
46ea4c3c98d2: Pull complete
Digest: sha256:a182c561bb28cac4d30edfaee21ebed3f06ec83f25ad1efec9324c67e7cb8d95
Status: Downloaded newer image for tingle/dependabot-azure-devops:0.3
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.7-compliant syntax, but you are running 2.6.6.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:444:in `rescue in default_branch_for_repo': Dependabot::RepoNotFound (Dependabot::RepoNotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:440:in `default_branch_for_repo'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:70:in `commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:359:in `_full_specification_for'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:174:in `_fetch_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:159:in `repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:102:in `fetch_file_if_present'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.142.1/lib/dependabot/python/file_fetcher.rb:116:in `pipfile'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.142.1/lib/dependabot/python/file_fetcher.rb:64:in `pipenv_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.142.1/lib/dependabot/python/file_fetcher.rb:41:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./update-script.rb:172:in `<main>'
/home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/clients/azure.rb:231:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/clients/azure.rb:57:in `fetch_default_branch'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:442:in `default_branch_for_repo'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:70:in `commit'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:359:in `_full_specification_for'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:174:in `_fetch_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:159:in `repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:102:in `fetch_file_if_present'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.142.1/lib/dependabot/python/file_fetcher.rb:116:in `pipfile'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.142.1/lib/dependabot/python/file_fetcher.rb:64:in `pipenv_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.142.1/lib/dependabot/python/file_fetcher.rb:41:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.142.1/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./update-script.rb:172:in `<main>'
Using 'bvacx.visualstudio.com' as hostname
Fetching pip dependency files for bvacx/PCX/_git/api-arena
Targeting 'default' branch under '/arena' directory
Using 'auto' versioning strategy
##[error]The process '/usr/bin/docker' failed with exit code 1```

**Comment by mburumaxwell** [comment]
Unfortunately, dependabot does not seem to work with the old URL. See the [recommended workaround](https://github.com/tinglesoftware/dependabot-azure-devops#still-using-the-old-visualstudiocom-url)
